
INSERT INTO   CONTBDEPTST.AUTORIZACOES_II               SELECT  *  FROM  AUTORIZACOES;
INSERT INTO   CONTBDEPTST.PROGRAMA_II                   SELECT  *  FROM  PROGRAMA    ;
INSERT INTO   CONTBDEPTST.BACIAS_PROGRAMA_II            SELECT  *  FROM  BACIAS_PROGRAMA;
INSERT INTO   CONTBDEPTST.EMPRESA_II                    SELECT  *  FROM  EMPRESA;
INSERT INTO   CONTBDEPTST.NATUREZA_AQUISICAO_II         SELECT  *  FROM  NATUREZA_AQUISICAO;
INSERT INTO   CONTBDEPTST.TECNOLOGIA_II                 SELECT  *  FROM  TECNOLOGIA;
INSERT INTO   CONTBDEPTST.TECNOLOGIA_VERSAO_II          SELECT  *  FROM  TECNOLOGIA_VERSAO;
INSERT INTO   CONTBDEPTST.UNIDADES_II                   SELECT  *  FROM  UNIDADES;
INSERT INTO   CONTBDEPTST.VERSAO_II                     SELECT  *  FROM  VERSAO;
INSERT INTO   CONTBDEPTST.PERF_REAL_ESPECIAIS_II        SELECT  *  FROM  PERF_REAL_ESPECIAIS;
INSERT INTO   CONTBDEPTST.BACIAS_II                     SELECT  *  FROM  BACIAS;
INSERT INTO   CONTBDEPTST.PERF_REAL_DURANTE_PERF_II     SELECT  *  FROM  PERF_REAL_DURANTE_PERF;
INSERT INTO   CONTBDEPTST.PERF_REAL_CONVENCIONAIS_II    SELECT  *  FROM  PERF_REAL_CONVENCIONAIS;
INSERT INTO   CONTBDEPTST.CONCESSIONARIOS_II            SELECT  *  FROM  CONCESSIONARIOS;
INSERT INTO   CONTBDEPTST.PERF_REALIZADAS_II            SELECT  *  FROM  PERF_REALIZADAS;
INSERT INTO   CONTBDEPTST.POCOS_LOGS_INTER_PBK_II       SELECT  *  FROM  POCOS_LOGS_INTER_PBK;
INSERT INTO   CONTBDEPTST.ESTADOS_II                    SELECT  *  FROM  ESTADOS;
INSERT INTO   CONTBDEPTST.OPERADOR_CONTRATO_II          SELECT  *  FROM  OPERADOR_CONTRATO;
INSERT INTO   CONTBDEPTST.POCOS_II                      SELECT  *  FROM  POCOS;
INSERT INTO   CONTBDEPTST.POCOS_LOGS_PBK_II             SELECT  *  FROM  POCOS_LOGS_PBK;

COMMIT;

exit;
