
TRUNCATE TABLE CONTBDEPTST.AUTORIZACOES_II;
TRUNCATE TABLE CONTBDEPTST.PROGRAMA_II;
TRUNCATE TABLE CONTBDEPTST.BACIAS_PROGRAMA_II;
TRUNCATE TABLE CONTBDEPTST.EMPRESA_II;
TRUNCATE TABLE CONTBDEPTST.NATUREZA_AQUISICAO_II;
TRUNCATE TABLE CONTBDEPTST.TECNOLOGIA_II;
TRUNCATE TABLE CONTBDEPTST.TECNOLOGIA_VERSAO_II;
TRUNCATE TABLE CONTBDEPTST.UNIDADES_II;
TRUNCATE TABLE CONTBDEPTST.VERSAO_II;
TRUNCATE TABLE CONTBDEPTST.PERF_REAL_ESPECIAIS_II;
TRUNCATE TABLE CONTBDEPTST.BACIAS_II;
TRUNCATE TABLE CONTBDEPTST.PERF_REAL_DURANTE_PERF_II;
TRUNCATE TABLE CONTBDEPTST.PERF_REAL_CONVENCIONAIS_II;
TRUNCATE TABLE CONTBDEPTST.CONCESSIONARIOS_II;
TRUNCATE TABLE CONTBDEPTST.PERF_REALIZADAS_II;
TRUNCATE TABLE CONTBDEPTST.POCOS_LOGS_INTER_PBK_II;
TRUNCATE TABLE CONTBDEPTST.ESTADOS_II;
TRUNCATE TABLE CONTBDEPTST.OPERADOR_CONTRATO_II;
TRUNCATE TABLE CONTBDEPTST.POCOS_II;
TRUNCATE TABLE CONTBDEPTST.POCOS_LOGS_PBK_II;

exit;