USE [MIDB60D]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_DBA_HISTORICO_CARGOS_SALARIOS]
	@CHAPA VARCHAR(16)  = NULL,
	@CHAVE_DECRYPT VARCHAR(10) = NULL
WITH ENCRYPTION, EXECUTE AS  CALLER
AS
-- EXEC SP_DBA_HISTORICO_CARGOS_SALARIOS '97016062', 'TESTE123'

DECLARE
	--@CHAPA					VARCHAR(16),
	--@CHAVE_DECRYPT			NVARCHAR(128),
	@CHAVE_ENCRYPT			VARCHAR(10),
	@ID_HIST_CARGO_SALARIO	INT,
	@NOME					VARCHAR(120),
	@DT_MUDANCA				DATETIME,
	@SALARIO_O				NUMERIC(15,2),
	@SALARIO				VARBINARY(256),
	@MOT_MUD_SAL			VARCHAR(50),
	@FUNCAO					VARCHAR(40),
	@MOT_MUD_FUNCAO			VARCHAR(50),
	@CMD					VARCHAR(1000),
	@KEY					VARCHAR(200)

IF EXISTS (SELECT * FROM tempdb.sys.objects WHERE name = '##TMP_HIST_CARGO_SALARIO')
	DROP TABLE ##TMP_HIST_CARGO_SALARIO

IF NOT EXISTS (SELECT * FROM tempdb.sys.objects WHERE name = '##TMP_HIST_CARGO_SALARIO')
	BEGIN
		CREATE TABLE ##TMP_HIST_CARGO_SALARIO (ID_HIST_CARGO_SALARIO INT NOT NULL IDENTITY (1, 1), CHAPA VARCHAR(16), NOME VARCHAR(120), DTMUDANCA DATETIME, 
		SALARIO_O NUMERIC(15,2), SALARIO VARBINARY(256), MOT_MUD_SAL VARCHAR(50), FUNCAO VARCHAR(40), MOT_MUD_FUNCAO VARCHAR(50))

		ALTER TABLE ##TMP_HIST_CARGO_SALARIO ADD CONSTRAINT PK_HIST_CARGO_SALARIO PRIMARY KEY CLUSTERED (ID_HIST_CARGO_SALARIO)
	END

SET @CHAPA = '97016062'
SET @CHAVE_DECRYPT = 'TESTE123'

DECLARE C_SAL_FUN CURSOR FOR 
	SELECT TOP(3) HS.CHAPA, UPPER(FU.NOME), 
		HS.DTMUDANCA, HS.SALARIO, UPPER(MS.DESCRICAO) 
	FROM [BD-ADM].CORPORERM.DBO.PFHSTSAL HS,
		[BD-ADM].CORPORERM.DBO.PFUNC FU,
		[BD-ADM].CORPORERM.DBO.PMOTMUDSAL MS
	WHERE HS.CHAPA = FU.CHAPA
		AND HS.CODCOLIGADA = FU.CODCOLIGADA
		AND HS.MOTIVO = MS.CODCLIENTE
		AND HS.CODCOLIGADA = MS.CODCOLIGADA
		AND HS.CHAPA = '97016062' --@CHAPA
		AND HS.CODCOLIGADA = 1
	ORDER BY HS.DTMUDANCA DESC

	OPEN C_SAL_FUN
	FETCH NEXT FROM C_SAL_FUN 
	INTO @CHAPA, @NOME, @DT_MUDANCA, @SALARIO_O, @MOT_MUD_SAL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT TOP(1) @FUNCAO = TT.FUNCAO,
			@MOT_MUD_FUNCAO = TT.MOT_MUD_FUNCAO
		FROM (SELECT HF.CHAPA, UPPER(FU.NOME) NOME, 
				HF.DTMUDANCA, UPPER(F.NOME) FUNCAO, UPPER(MF.DESCRICAO) MOT_MUD_FUNCAO
				FROM [BD-ADM].CORPORERM.DBO.PFHSTFCO HF,
				     [BD-ADM].CORPORERM.DBO.PFUNCAO F,
				     [BD-ADM].CORPORERM.DBO.PFUNC FU,
				     [BD-ADM].CORPORERM.DBO.PMOTMUDFUNCAO MF
				WHERE HF.CODFUNCAO = F.CODIGO
				AND HF.CODCOLIGADA = F.CODCOLIGADA
				AND HF.CHAPA = FU.CHAPA
				AND HF.CODCOLIGADA = FU.CODCOLIGADA
				AND HF.MOTIVO = MF.CODCLIENTE
				AND HF.CODCOLIGADA = MF.CODCOLIGADA
				AND HF.CHAPA = @CHAPA
				AND HF.CODCOLIGADA = 1) TT
		WHERE TT.DTMUDANCA <= @DT_MUDANCA
			AND TT.CHAPA = @CHAPA
		ORDER BY TT.DTMUDANCA DESC

		INSERT INTO ##TMP_HIST_CARGO_SALARIO (CHAPA, NOME, DTMUDANCA, SALARIO_O, MOT_MUD_SAL, FUNCAO, MOT_MUD_FUNCAO)
		VALUES (@CHAPA, @NOME, @DT_MUDANCA, @SALARIO_O, @MOT_MUD_SAL, @FUNCAO, @MOT_MUD_FUNCAO)

		FETCH NEXT FROM C_SAL_FUN
		INTO @CHAPA, @NOME, @DT_MUDANCA, @SALARIO_O, @MOT_MUD_SAL
	END

	CLOSE C_SAL_FUN
	DEALLOCATE C_SAL_FUN
	
	SET @CHAVE_ENCRYPT = 'TESTE123'

	UPDATE ##TMP_HIST_CARGO_SALARIO
	SET SALARIO = EncryptByPassPhrase(CONVERT(NVARCHAR,@CHAVE_ENCRYPT), CONVERT(VARBINARY,SALARIO_O),1, CONVERT(VARBINARY,ID_HIST_CARGO_SALARIO))
	
	UPDATE ##TMP_HIST_CARGO_SALARIO
	SET SALARIO_O = NULL


	SET @KEY = 'CONVERT(NUMERIC(15,2),DecryptByPassphrase(CONVERT(NVARCHAR,'+ CHAR(39)+ CAST(@CHAVE_DECRYPT AS VARCHAR(10)) + CHAR(39) +'), SALARIO, 1, CONVERT(VARBINARY,ID_HIST_CARGO_SALARIO)))'

	IF (@CHAVE_DECRYPT <> @CHAVE_ENCRYPT ) OR @CHAVE_DECRYPT IS NULL
		EXEC ('SELECT CHAPA MATRICULA, NOME, DTMUDANCA DT_MUDANCA, SALARIO,
				MOT_MUD_SAL MOTIVO_MUDANCA_SAL, FUNCAO, MOT_MUD_FUNCAO MOTIVO_MUDANCA_FNC
				FROM ##TMP_HIST_CARGO_SALARIO')
	ELSE
		BEGIN
			SET @CMD = 'SELECT CHAPA MATRICULA, NOME, DTMUDANCA DT_MUDANCA, ' 
						+ @KEY + ' SALARIO, MOT_MUD_SAL MOTIVO_MUDANCA_SAL, FUNCAO, MOT_MUD_FUNCAO MOTIVO_MUDANCA_FNC FROM ##TMP_HIST_CARGO_SALARIO'
						
			PRINT 	(@CMD)	
			EXEC (@CMD)
		END
GO