
--  EXEC SP_DBA_HISTORICO_CARGOS_SALARIOS '80005333'

DECLARE @CHAVE_DECRYPT NVARCHAR(128)

SET @CHAVE_DECRYPT = 'SigiloTotaL'

SELECT CHAPA MATRICULA, NOME, DTMUDANCA DT_MUDANCA,
CONVERT(NUMERIC(15,2),DecryptByPassphrase(CHAR(39) + @CHAVE_DECRYPT + CHAR(39), SALARIO, 1, CONVERT(VARBINARY,ID_HIST_CARGO_SALARIO))) SALARIO,
MOT_MUD_SAL MOTIVO_MUDANCA_SAL, FUNCAO, MOT_MUD_FUNCAO MOTIVO_MUDANCA_FNC
FROM ##TMP_HIST_CARGO_SALARIO