IF EXISTS (SELECT * FROM tempdb.sys.objects WHERE name = '##TMP_HIST_CARGO_SALARIO')
	DROP TABLE ##TMP_HIST_CARGO_SALARIO

IF NOT EXISTS (SELECT * FROM tempdb.sys.objects WHERE name = '##TMP_HIST_CARGO_SALARIO')
	BEGIN
		CREATE TABLE ##TMP_HIST_CARGO_SALARIO (ID_HIST_CARGO_SALARIO INT NOT NULL IDENTITY (1, 1), CHAPA VARCHAR(16), NOME VARCHAR(120), DTMUDANCA DATETIME,
		SALARIO NUMERIC(15,2), MOT_MUD_SAL VARCHAR(50), FUNCAO VARCHAR(40), MOT_MUD_FUNCAO VARCHAR(50))

		ALTER TABLE ##TMP_HIST_CARGO_SALARIO ADD CONSTRAINT PK_HIST_CARGO_SALARIO PRIMARY KEY CLUSTERED (ID_HIST_CARGO_SALARIO)
	END

DECLARE
@MATRICULA		VARCHAR(16),
@NOME			VARCHAR(120),
@DT_MUDANCA		DATETIME,
@SALARIO		NUMERIC(15,2),
@MOT_MUD_SAL	VARCHAR(50),
@FUNCAO			VARCHAR(40),
@MOT_MUD_FUNCAO	VARCHAR(50)

SET @MATRICULA = '80005333'

DECLARE C_SAL_FUN CURSOR FOR 
	SELECT DISTINCT TOP(10) MATRICULA, NOME, DT_MUDANCA, SALARIO, MOT_MUD_SAL
	FROM VW_SAL S
	WHERE MATRICULA = @MATRICULA
	ORDER BY DT_MUDANCA DESC

	OPEN C_SAL_FUN
	FETCH NEXT FROM C_SAL_FUN 
	INTO @MATRICULA, @NOME, @DT_MUDANCA, @SALARIO, @MOT_MUD_SAL

	WHILE @@FETCH_STATUS = 0
	BEGIN
		SELECT TOP(1) @FUNCAO = FUNCAO,
		@MOT_MUD_FUNCAO = MOT_MUD_FUN
		FROM VW_FUN
		WHERE DT_MUDANCA <= @DT_MUDANCA
		AND MATRICULA = @MATRICULA
		ORDER BY DT_MUDANCA DESC

		INSERT INTO ##TMP_HIST_CARGO_SALARIO (CHAPA, NOME, DTMUDANCA, SALARIO, MOT_MUD_SAL, FUNCAO, MOT_MUD_FUNCAO)
		VALUES (@MATRICULA, @NOME, @DT_MUDANCA, @SALARIO, @MOT_MUD_SAL, @FUNCAO, @MOT_MUD_FUNCAO)

		FETCH NEXT FROM C_SAL_FUN
		INTO @MATRICULA, @NOME, @DT_MUDANCA, @SALARIO, @MOT_MUD_SAL
	END

	CLOSE C_SAL_FUN
	DEALLOCATE C_SAL_FUN

SELECT CHAPA, NOME, DTMUDANCA, SALARIO, MOT_MUD_SAL, FUNCAO FROM ##TMP_HIST_CARGO_SALARIO
ORDER BY 4 DESC