
--  CREATE SYNONYM SAC_CATEGORIA FOR [111677].SAC_CATEGORIA
SELECT 'CREATE SYNONYM ' + NAME + ' FOR [111677].' + NAME 
FROM SYS.ALL_OBJECTS
WHERE TYPE_DESC = 'USER_TABLE'

--  GRANT EXECUTE ON [111677].USP_SAC_ALTERA_CONDICAO_PAGAMENTO TO R_SAC
SELECT 'GRANT EXECUTE ON [111677].' + NAME + ' TO R_SAC' FROM sys.all_objects
WHERE TYPE_DESC = 'SQL_STORED_PROCEDURE'
AND NAME LIKE 'USP_SAC%'