SELECT DB_NAME(DBID) AS BASE, STR(CONVERT(DEC(15),SUM(SIZE))* 8192/ 1073741824,10,2)+ N' GB' AS SIZE 
FROM SYS.SYSALTFILES
WHERE DB_NAME(DBID) NOT IN ('MSDB','TEMPDB','MODEL','MASTER')
GROUP BY DBID 
ORDER BY 2 DESC
GO