SELECT grantee, owner, table_name, grantor, INITCAP(PRIVILEGE) PRIVILEGE,
       INITCAP(grantable) grantable, INITCAP(HIERARCHY) HIERARCHY
FROM   DBA_TAB_PRIVS
WHERE  (GRANTEE = 'sys' OR GRANTEE IN ('CRP'))
AND    TABLE_NAME NOT LIKE 'BIN$%'
ORDER  BY GRANTEE, OWNER, TABLE_NAME, Privilege