---- # Efetua limpesa das tabelas Corporativas contbdeptst ( (Bdep/berilo)SIRCS, SCP) 

TRUNCATE TABLE CONTBDEPTST.AUTORIZACOES;
TRUNCATE TABLE CONTBDEPTST.PROGRAMA;
TRUNCATE TABLE CONTBDEPTST.BACIAS_PROGRAMA;
TRUNCATE TABLE CONTBDEPTST.EMPRESA;
TRUNCATE TABLE CONTBDEPTST.NATUREZA_AQUISICAO;
TRUNCATE TABLE CONTBDEPTST.TECNOLOGIA;
TRUNCATE TABLE CONTBDEPTST.TECNOLOGIA_VERSAO;
TRUNCATE TABLE CONTBDEPTST.UNIDADES;
TRUNCATE TABLE CONTBDEPTST.VERSAO;
TRUNCATE TABLE CONTBDEPTST.PERF_REAL_ESPECIAIS;
TRUNCATE TABLE CONTBDEPTST.BACIAS;
TRUNCATE TABLE CONTBDEPTST.PERF_REAL_DURANTE_PERF;
TRUNCATE TABLE CONTBDEPTST.PERF_REAL_CONVENCIONAIS;
TRUNCATE TABLE CONTBDEPTST.CONCESSIONARIOS;
TRUNCATE TABLE CONTBDEPTST.PERF_REALIZADAS;
TRUNCATE TABLE CONTBDEPTST.POCOS_LOGS_INTER_PBK;
TRUNCATE TABLE CONTBDEPTST.ESTADOS;
TRUNCATE TABLE CONTBDEPTST.OPERADOR_CONTRATO;
TRUNCATE TABLE CONTBDEPTST.POCOS;
TRUNCATE TABLE CONTBDEPTST.POCOS_LOGS_PBK;

exit;