SET PAGES 0      ;
SET LINES 120	 ;
SET FEEDBACK OFF ;
SET VERIFY OFF;
-- ACCEPT STATUS PROMPT 'ENTRE COM O STATUS DO TRIGGER: ' ;

SPOOL ENABLETRIGGER.LST;

SELECT TRIGGER_NAME , STATUS
FROM USER_TRIGGERS
WHERE STATUS = UPPER('&1') ;

SPOOL OFF ;

SET PAGESIZE 24 ;
SET FEEDBACK ON ;
SET VERIFY ON;


--@C:\SQL\ENABLETRIGGER.LST;

-- @use : @c:\...\_GetTriggerStatus (parametro)
-- parametro = ENABLE ou DISABLED
