SELECT NAME, MASTER_VIEW, MASTER_OWNER, OWNER, REFRESH_MODE, REFRESH_GROUP, LAST_REFRESH, next,  error FROM DBA_SNAPSHOTS
WHERE OWNER = 'ODS'
ORDER BY NAME



-- REFRESH_GROUP=61 É O GRUPO_01
SELECT NAME, MASTER_VIEW, MASTER_OWNER, OWNER, REFRESH_MODE, REFRESH_GROUP, LAST_REFRESH, next,  error FROM DBA_SNAPSHOTS
WHERE OWNER = 'CRMPS8'
AND REFRESH_GROUP = 61
ORDER BY NAME


-- LISTAR OS GRUPOS DE REFRESH
SELECT * FROM dba_rgroup
ORDER BY 1


-- VERIFICAR SE ALGUM GRUPO ESTÁ COM PROBLEMA
SELECT * FROM dba_REFRESH
WHERE  ROWNER = 'ODS'
ORDER BY 1