-- Retira o status "BROKEN" e seta o próximo refresh em 15 minutos
     SYS.DBMS_IJOB.BROKEN(p_job_id, FALSE, SYSDATE+(15/1440)); 
     COMMIT;


-- EXECUTAR JOB MANUALMENTE
EXECUTE DBMS_SCHEDULER.RUN_JOB ('"EAI"."ODS_PS8_CHAMADOS_CALC_SLA"' , FALSE) 

-- PARAR JOB MANUALMENTE
EXECUTE DBMS_SCHEDULER.stop_job ('"EAI"."ODS_PS8_CHAMADOS_CALC_SLA"')