create table ADP.TIMESHEET_TMP (

COD_FUNCIONARIO      VARCHAR2(54), 
COD_PROJETO_TS       VARCHAR2(54),
HRS_LANCADA          NUMBER(10,7),
DAT_LANCAMENTO       DATE,          
TAREFA               VARCHAR2(240), 
USU_ALTERACAO        VARCHAR2(150), 
DAT_ALTERACAO        DATE,          
USU_CRIACAO          VARCHAR2(150), 
DAT_CRIACAO          DATE,          
CHV_ORIGEM           NUMBER(15)   )

  
  ORGANIZATION EXTERNAL
  (
    TYPE ORACLE_LOADER DEFAULT DIRECTORY "DIR_CARGA_ADP" ACCESS PARAMETERS ( RECORDS DELIMITED BY NEWLINE FIELDS TERMINATED BY '|' ) LOCATION ( "DIR_CARGA_ADP":' timesheet.csv' )
  )
  REJECT LIMIT UNLIMITED ;