BEGIN
DBMS_REFRESH.MAKE (NAME => '"CSN"."GRUPO_01"',
   LIST => '"CSN"."FND_USER"',
   NEXT_DATE => SYSDATE +3,
   INTERVAL => 'TRUNC(SYSDATE+1)+5/24',
   IMPLICIT_DESTROY => TRUE,
   LAX => FALSE,
   JOB => 0,
   ROLLBACK_SEG => NULL,
   PUSH_DEFERRED_RPC => NULL,
   REFRESH_AFTER_ERRORS => NULL,
   PURGE_OPTION => NULL,
   PARALLELISM => NULL,
   HEAP_SIZE => NULL
  );
  END;