-- CRIANDO USUARIO:

CREATE TABLESPACE "DWATENDIMENTO_S_DAT" DATAFILE 'M:\ORACLE\ORADATA\ODSSTG\DW_ATENDIMENTO_S_DAT_01.DBF' SIZE 10M AUTOEXTEND ON; 
CREATE TABLESPACE "DWATENDIMENTO_S_IDX" DATAFILE 'M:\ORACLE\ORADATA\ODSSTG\DW_ATENDIMENTO_S_IDX_01.DBF' SIZE 10M AUTOEXTEND ON;


create user DWATENDIMENTO
identified by G6hr17
default tablespace DWATENDIMENTO_S_DAT
quota unlimited on DWATENDIMENTO_S_DAT
quota unlimited on DWATENDIMENTO_S_IDX;


create role ROLE_DWATENDIMENTO_READ;
create role ROLE_DWATENDIMENTO_WRITE;  




-- DROPANDO USUARIO:

DROP USER USR CASCADE;


-- LOCK DE CONTA:

ALTER USER USR LOCK ACCOUNT;