-- FUNCIONANDO
-- OK
SELECT decode(O.OBJECT_TYPE,
'SEQUENCE','GRANT SELECT ON '||O.OWNER||'.',
'PROCEDURE','GRANT EXECUTE ON '||O.OWNER||'.',
'PACKAGE','GRANT EXECUTE ON '||O.OWNER||'.',
'FUNCTION','GRANT EXECUTE ON '||O.OWNER||'.')||O.OBJECT_NAME|| ' TO ROLE_' ||O.OWNER||'_WRITE ;'
FROM DBA_OBJECTS O, DBA_ROLE_PRIVS R
WHERE OBJECT_TYPE IN ('SEQUENCE', 'PROCEDURE', 'PACKAGE','FUNCTION')
AND R.GRANTED_ROLE = (SELECT 'ROLE_' ||OWNER||'_WRITE' FROM DUAL)
ORDER BY O.OBJECT_TYPE


-- OK--- COM REDUNDÂNCIA
SELECT decode(O.OBJECT_TYPE,
'TABLE','GRANT SELECT ON '||O.OWNER||'.',
'VIEW','GRANT SELECT ON '||O.OWNER||'.')||O.OBJECT_NAME|| ' TO ROLE_' ||O.OWNER||'_READ ;'
FROM DBA_OBJECTS O, DBA_ROLE_PRIVS R
WHERE OBJECT_TYPE IN ('TABLE','VIEW')
AND R.GRANTED_ROLE = (SELECT 'ROLE_' ||OWNER||'_READ' FROM DUAL)
ORDER BY O.OBJECT_TYPE











VERSÕES FINAIS


select 'GRANT SELECT ON '||O.OWNER||'.'||O.OBJECT_NAME|| ' TO ROLE_' ||O.OWNER||'_READ ;'
from DBA_OBJECTS O--, DBA_TAB_PRIVS T
where O.OBJECT_TYPE in ('TABLE','VIEW')
--and T.GRANTEE = (select distinct 'ROLE_' ||O.OWNER||'_READ' from DUAL)
--and O.OWNER = T.OWNER
and O.OWNER like '%CRMPS8%'
ORDER BY O.OBJECT_TYPE


-- GRANT DE INSERT NAS TABELAS PARA O WRITE

SELECT decode(O.OBJECT_TYPE,
'TABLE','GRANT INSERT, DELETE, UPDATE ON '||O.OWNER||'.',
'SEQUENCE','GRANT SELECT ON '||O.OWNER||'.',
'PROCEDURE','GRANT EXECUTE ON '||O.OWNER||'.',
'PACKAGE','GRANT EXECUTE ON '||O.OWNER||'.',
'FUNCTION','GRANT EXECUTE ON '||O.OWNER||'.')||O.OBJECT_NAME|| ' TO ROLE_' ||O.OWNER||'_WRITE ;'
FROM DBA_OBJECTS O, DBA_ROLE_PRIVS R
WHERE OBJECT_TYPE IN ('SEQUENCE', 'PROCEDURE', 'PACKAGE','FUNCTION', 'TABLE')
AND R.GRANTED_ROLE = (SELECT 'ROLE_' ||OWNER||'_WRITE' FROM DUAL)
AND OWNER = 'ESBJMS'
ORDER BY O.OBJECT_TYPE






