-- ORIGINAL
SELECT decode(object_type,
'TABLE','GRANT SELECT ON'||&OWNER||'.',
'VIEW','GRANT SELECT ON '||&OWNER||'.',
'SEQUENCE','GRANT SELECT ON '||&OWNER||'.',
'PROCEDURE','GRANT EXECUTE ON '||&OWNER||'.',
'PACKAGE','GRANT EXECUTE ON '||&OWNER||'.',
'FUNCTION','GRANT EXECUTE ON'||&OWNER||'.' )||object_name||' TO ROLE_' ||&OWNER|| '_READ ;'
FROM user_objects
WHERE OBJECT_TYPE IN ( 'TABLE', 'VIEW', 'SEQUENCE', 'PROCEDURE', 'PACKAGE','FUNCTION')
Order By Object_Type





-- FUNCIONANDO
-- OK
SELECT decode(O.OBJECT_TYPE,
'SEQUENCE','GRANT SELECT ON '||O.OWNER||'.',
'PROCEDURE','GRANT EXECUTE ON '||O.OWNER||'.',
'PACKAGE','GRANT EXECUTE ON '||O.OWNER||'.',
'FUNCTION','GRANT EXECUTE ON '||O.OWNER||'.')||O.OBJECT_NAME|| ' TO ROLE_' ||O.OWNER||'_WRITE ;'
FROM DBA_OBJECTS O, DBA_ROLE_PRIVS R
WHERE OBJECT_TYPE IN ('SEQUENCE', 'PROCEDURE', 'PACKAGE','FUNCTION')
AND R.GRANTED_ROLE = (SELECT 'ROLE_' ||OWNER||'_WRITE' FROM DUAL)
ORDER BY O.OBJECT_TYPE


-- OK
SELECT decode(O.OBJECT_TYPE,
'TABLE','GRANT SELECT ON '||O.OWNER||'.',
'VIEW','GRANT SELECT ON '||O.OWNER||'.')||O.OBJECT_NAME|| ' TO ROLE_' ||O.OWNER||'_READ ;'
FROM DBA_OBJECTS O, DBA_ROLE_PRIVS R
WHERE OBJECT_TYPE IN ('TABLE','VIEW')
AND R.GRANTED_ROLE = (SELECT 'ROLE_' ||OWNER||'_WRITE' FROM DUAL)
ORDER BY O.OBJECT_TYPE














