-- Verificar os jobs que estão rodando

SELECT * FROM dba_scheduler_running_jobs

-- QUERY PARA PEGAR O ERRO OCORRIDO COM O NOME DO JOB QUE FALHOU

SELECT LOG_ID, JOB_NAME, JOB_SUBNAME, STATUS, ADDITIONAL_INFO
FROM dba_scheduler_job_run_details
WHERE STATUS = 'FAILED'


-- PARANDO UM JOB

DBMS_SCHEDULER.STOP_JOB (
   job_name         IN VARCHAR2
   force            IN BOOLEAN DEFAULT FALSE);


-- VERIFICAR TODOS OS JOBS QUE ESTÃO COM ERRO ORDENADOS POR DATA  

SELECT LOG_ID, LOG_DATE, JOB_NAME, JOB_SUBNAME, STATUS, ADDITIONAL_INFO
FROM dba_scheduler_job_run_details
WHERE STATUS = 'FAILED'
ORDER BY LOG_DATE DESC


-- VERIFICAR JOBS COM STATUS DIFERENTE DE SUCCEEDED

SELECT LOG_ID, LOG_DATE, JOB_NAME, JOB_SUBNAME, STATUS, ADDITIONAL_INFO
FROM dba_scheduler_job_run_details
WHERE STATUS <> 'SUCCEEDED'
ORDER BY LOG_DATE DESC