CREATE DATABASE teste
   MAXINSTANCES 2
   MAXLOGFILES 16
   MAXLOGMEMBERS 3
   MAXLOGHISTORY 1
   MAXDATAFILES 100
   DATAFILE 'C:\app\lf\oradata\orcl2\system01.dbf' SIZE 300M REUSE AUTOEXTEND ON NEXT 10240K MAXSIZE UNLIMITED 
   EXTENT MANAGEMENT LOCAL
   SYSAUX DATAFIL "C:\app\lf\oradata\orcl2\sysaux01.dbf" SIZE 120M REUSE 
   DEFAULT TEMPORARY TABLESPACE temp 
	TEMPFILE 'C:\app\lf\oradata\orcl2\temp01.dbf' 
        SIZE 10M REUSE AUTOEXTEND ON NEXT 640K MAXSIZE UNLIMITED
   UNDO TABLESPACE undotbs1
      DATAFILE 'C:\app\lf\oradata\orcl2\undotbs01.dbf'
      SIZE 200M REUSE AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
   CHARACTER SET US7ASCII
   NATIONAL CHARACTER SET AL16UTF16
   LOGFILE GROUP 1 ('C:\app\lf\oradata\orcl2\redo01.log') SIZE 10M,
           GROUP 2 ('C:\app\lf\oradata\orcl2\redo02.log') SIZE 10M,
           GROUP 3 ('C:\app\lf\oradata\orcl2\redo03.log') SIZE 10M;

