SET PAGESIZE 0 ;
SET FEEDBACK OFF ;
SET VERIFY OFF;

SPOOL C:\SQL\DROPESQ.LST
SELECT 'DROP '||OBJECT_TYPE || ' '|| 
       DECODE(OBJECT_TYPE,'DATABASE LINK' , OBJECT_NAME ,
       '"'||OBJECT_NAME||'"') ||
       DECODE(OBJECT_TYPE,'TABLE',' CASCADE CONSTRAINTS ; ',' ;')
FROM USER_OBJECTS
WHERE OBJECT_TYPE NOT IN ('INDEX','TRIGGER','PACKAGE BODY', 'LOB')
AND OBJECT_NAME NOT LIKE 'BIN$%' ;
SPOOL OFF ;
SET PAGESIZE 24 ;
SET FEEDBACK ON ;
SET VERIFY ON;