SET PAGES 0      ;
SET LINES 120	 ;
SET FEEDBACK OFF ;
SPOOL C:\SQL\DROPTRIGGER.LST;

SELECT 'DROP TRIGGER '|| OBJECT_NAME || ';'
FROM USER_OBJECTS
WHERE OBJECT_TYPE = 'TRIGGER'
AND STATUS = 'INVALID';

SPOOL OFF ;

SET PAGESIZE 24 ;
SET FEEDBACK ON ;
SET VERIFY ON;

@C:\SQL\DROPTRIGGER.LST;