SET PAGESIZE 0 ;
SET FEEDBACK OFF ;
SET VERIFY OFF;
ACCEPT ESQUEMA PROMPT 'ENTRE COM O NOME DO ESQUEMA/USUARIO : ' ;
SPOOL C:\SQL\DROPESQ.LST
SELECT 'DROP '||OBJECT_TYPE || ' '|| 
       DECODE(OBJECT_TYPE,'DATABASE LINK' , OBJECT_NAME ,
       OWNER||'.'||'"'||OBJECT_NAME||'"') ||
       DECODE(OBJECT_TYPE,'TABLE',' CASCADE CONSTRAINTS ; ',' ;')
FROM DBA_OBJECTS
WHERE OWNER=UPPER('&ESQUEMA') 
AND OBJECT_TYPE NOT IN ('INDEX','TRIGGER','PACKAGE BODY', 'LOB')
AND OBJECT_NAME NOT LIKE 'BIN$%' ;
SPOOL OFF ;
SET PAGESIZE 24 ;
SET FEEDBACK ON ;
SET VERIFY ON;