set termout off;                                                                                                                                                                                                                                                                                            
spool idx2.lst;                                                                                                                                                                                                                                                                                             
column card format 9,999,999;                                                                                                                                                                                                                                                                               
select distinct count(distinct GEO_LOC_CD) card, ' is the cardinality of Index GEO_LOC_PK on column GEO_LOC_CD of table RPT.GEO_LOC' from RPT.GEO_LOC;                                                                                                                                                      
select distinct count(distinct GEO_LOC_TY_CD) card, ' is the cardinality of Index GEO_LOC_PK on column GEO_LOC_TY_CD of table RPT.GEO_LOC' from RPT.GEO_LOC;                                                                                                                                                
select distinct count(distinct GEO_LOC_CD_PRNT) card, ' is the cardinality of Index GLO_FK_GLO on column GEO_LOC_CD_PRNT of table RPT.GEO_LOC' from RPT.GEO_LOC;                                                                                                                                            
select distinct count(distinct GEO_LOC_TY_CD_PRNT) card, ' is the cardinality of Index GLO_FK_GLO on column GEO_LOC_TY_CD_PRNT of table RPT.GEO_LOC' from RPT.GEO_LOC;                                                                                                                                      
select distinct count(distinct ZONE_CD) card, ' is the cardinality of Index GLO_FK_ZNE on column ZONE_CD of table RPT.GEO_LOC' from RPT.GEO_LOC;                                                                                                                                                            
spool off;                                                                                                                                                                                                                                                                                                  
