spool D:\orant\database\spoolmain
set echo on
connect INTERNAL/<SENHA>
startup nomount pfile=e:\orant\database\init<SID>.ora
CREATE DATABASE <SID>
LOGFILE 'e:\orant\database\log<SID>1.ora' SIZE 1024K,
    'e:\orant\database\log<SID>2.ora' SIZE 1024K
MAXLOGFILES 32 
MAXLOGMEMBERS 2
MAXLOGHISTORY 1
DATAFILE 'e:\orant\database\Sys1<SID>.ora' SIZE 80M
MAXDATAFILES 254
MAXINSTANCES 1
CHARACTER SET WE8ISO8859P1
NATIONAL CHARACTER SET WE8ISO8859P1;
ALTER DATABASE DATAFILE 'e:\orant\database\Sys1<SID>.ora' AUTOEXTEND ON;
CREATE ROLLBACK SEGMENT SYSROL TABLESPACE "SYSTEM" STORAGE (INITIAL 100K NEXT 100K);
ALTER ROLLBACK SEGMENT "SYSROL" ONLINE;
@D:\orant\Rdbms80\admin\catalog.sql;
@D:\orant\Rdbms80\admin\catproc.sql
@D:\orant\Rdbms80\admin\caths.sql

REM **************TABLESPACE FOR ROLLBACK*****************
CREATE TABLESPACE RBS DATAFILE 'e:\orant\database\Rbs1<SID>.ora' SIZE 240M
DEFAULT STORAGE ( INITIAL 1024K NEXT 1024K MINEXTENTS 2 MAXEXTENTS 121 PCTINCREASE 0);
ALTER DATABASE DATAFILE 'e:\orant\database\Rbs1<SID>.ora' AUTOEXTEND ON;

REM ***********Alter system tablespace ********************
ALTER TABLESPACE SYSTEM
DEFAULT STORAGE ( INITIAL 100K NEXT 100K MINEXTENTS 1 MAXEXTENTS 300 PCTINCREASE 1);

REM **************TABLESPACE FOR USER*********************
CREATE TABLESPACE USR DATAFILE 'e:\orant\database\Usr1<SID>.ora' SIZE 10M
DEFAULT STORAGE ( INITIAL 50K NEXT 50K MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 1);
ALTER DATABASE DATAFILE 'e:\orant\database\Usr1<SID>.ora' AUTOEXTEND ON;

REM **************TABLESPACE FOR TEMPORARY*****************
CREATE TABLESPACE TEMPORARY DATAFILE 'e:\orant\database\Tmp1<SID>.ora' SIZE 100M
DEFAULT STORAGE ( INITIAL 100K NEXT 100K MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 0) TEMPORARY;
ALTER DATABASE DATAFILE 'e:\orant\database\Tmp1<SID>.ora' AUTOEXTEND ON;

REM **************TABLESPACE FOR INDEX*********************
CREATE TABLESPACE INDX DATAFILE 'e:\orant\database\Indx1<SID>.ora' SIZE 10M
DEFAULT STORAGE ( INITIAL 50K NEXT 50K MINEXTENTS 1 MAXEXTENTS 121 PCTINCREASE 1);
ALTER DATABASE DATAFILE 'e:\orant\database\Indx1<SID>.ora' AUTOEXTEND ON;

REM **** Creating two rollback segments ****************
CREATE PUBLIC ROLLBACK SEGMENT RB0 TABLESPACE "RBS"
STORAGE ( INITIAL 1000K NEXT 500K MINEXTENTS 2 MAXEXTENTS 10 );
CREATE PUBLIC ROLLBACK SEGMENT RB1 TABLESPACE "RBS"
STORAGE ( INITIAL 1000K NEXT 500K MINEXTENTS 2 MAXEXTENTS 10 );
CREATE PUBLIC ROLLBACK SEGMENT RB2 TABLESPACE "RBS"
STORAGE ( INITIAL 1000K NEXT 500K MINEXTENTS 2 MAXEXTENTS 10 );
CREATE PUBLIC ROLLBACK SEGMENT RB3 TABLESPACE "RBS"
STORAGE ( INITIAL 1000K NEXT 500K MINEXTENTS 2 MAXEXTENTS 10 );
ALTER ROLLBACK SEGMENT "RB0" ONLINE;
ALTER ROLLBACK SEGMENT "RB1" ONLINE;
ALTER ROLLBACK SEGMENT "RB2" ONLINE;
ALTER ROLLBACK SEGMENT "RB3" ONLINE;
alter user sys temporary tablespace TEMPORARY;
alter user system default tablespace USR;
alter rollback segment "SYSROL" offline;
spool off

