alter system set audit_trail = DB scope=spfile;

AUDIT
ALTER ANY INDEX, ALTER ANY PROCEDURE, ALTER ANY ROLE, ALTER ANY SEQUENCE, ALTER ANY SNAPSHOT, ALTER ANY TABLE,
ALTER ANY TRIGGER, ALTER DATABASE, ALTER ROLLBACK SEGMENT, ALTER TABLESPACE, ALTER USER, ANALYZE ANY,
CREATE ANY INDEX, GRANT ANY ROLE, CREATE ANY PROCEDURE, CREATE ANY SEQUENCE, CREATE ANY SNAPSHOT,
CREATE ANY SYNONYM, CREATE ANY TABLE, CREATE ANY TRIGGER, CREATE ANY VIEW, CREATE USER, DROP ANY INDEX,
DROP ANY PROCEDURE, DROP ANY SEQUENCE, DROP ANY SNAPSHOT, DROP ANY SYNONYM, DROP ANY TABLE, DROP ANY TRIGGER,
DROP ANY VIEW, DROP PUBLIC SYNONYM, DROP ROLLBACK SEGMENT, DROP USER, GRANT ANY PRIVILEGE, CREATE TABLE
BY ACCESS
WHENEVER SUCCESSFUL; 