

CREATE USER OPS$COLETORDp29
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp29;
  ALTER USER OPS$COLETORDp29 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp29;

CREATE USER OPS$COLETORDp30
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp30;
  ALTER USER OPS$COLETORDp30 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp30;


CREATE USER OPS$COLETORDp31
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp31;
  ALTER USER OPS$COLETORDp31 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp31;



CREATE USER OPS$COLETORDp32
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp32;
  ALTER USER OPS$COLETORDp32 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp32;



CREATE USER OPS$COLETORDp35
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp35;
  ALTER USER OPS$COLETORDp35 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp35;



CREATE USER OPS$COLETORDp36
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp36;
  ALTER USER OPS$COLETORDp36 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp36;


CREATE USER OPS$COLETORDp38
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp38;
  ALTER USER OPS$COLETORDp38 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp38;


CREATE USER OPS$COLETORDp44
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp44;
  ALTER USER OPS$COLETORDp44 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp44;


CREATE USER OPS$COLETORDp70
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp70;
  ALTER USER OPS$COLETORDp70 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp70;


CREATE USER OPS$COLETORDp71
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp71;
  ALTER USER OPS$COLETORDp71 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp71;



CREATE USER OPS$COLETORDp72
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp72;
  ALTER USER OPS$COLETORDp72 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp72;


CREATE USER OPS$COLETORDp80
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp80;
  ALTER USER OPS$COLETORDp80 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp80;



CREATE USER OPS$COLETORDp81
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp81;
  ALTER USER OPS$COLETORDp81 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp81;



CREATE USER OPS$COLETORDp82
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp82;
  ALTER USER OPS$COLETORDp82 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp82;



CREATE USER OPS$COLETORDp83
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp83;
  ALTER USER OPS$COLETORDp83 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp83;



CREATE USER OPS$COLETORDp84
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp84;
  ALTER USER OPS$COLETORDp84 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp84;



CREATE USER OPS$COLETORDp85
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp85;
  ALTER USER OPS$COLETORDp85 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp85;




CREATE USER OPS$COLETORDp86
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp86;
  ALTER USER OPS$COLETORDp86 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp86;




CREATE USER OPS$COLETORDp88
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp88;
  ALTER USER OPS$COLETORDp88 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp88;





CREATE USER OPS$COLETORDp89
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETORDp89;
  ALTER USER OPS$COLETORDp89 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETORDp89;





CREATE USER OPS$COLETOREM28
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM28;
  ALTER USER OPS$COLETOREM28 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM28;




CREATE USER OPS$COLETOREM39
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM39;
  ALTER USER OPS$COLETOREM39 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM39;




CREATE USER OPS$COLETOREM40
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM40;
  ALTER USER OPS$COLETOREM40 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM40;





CREATE USER OPS$COLETOREM51
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM51;
  ALTER USER OPS$COLETOREM51 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM51;






CREATE USER OPS$COLETOREM52
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM52;
  ALTER USER OPS$COLETOREM52 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM52;


CREATE USER OPS$COLETOREM67
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM67;
  ALTER USER OPS$COLETOREM67 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM67;


CREATE USER OPS$COLETOREM68
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM68;
  ALTER USER OPS$COLETOREM68 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM68;



CREATE USER OPS$COLETOREM69
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM69;
  ALTER USER OPS$COLETOREM69 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM69;


CREATE USER OPS$COLETOREM73
  IDENTIFIED EXTERNALLY
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  GRANT R_COLETOR TO OPS$COLETOREM73;
  ALTER USER OPS$COLETOREM73 DEFAULT ROLE ALL;
  GRANT CREATE SESSION TO OPS$COLETOREM73;