SELECT OWNER||'.'||INDEX_NAME INDEX_NAME
  FROM DBA_INDEXES
 WHERE OWNER NOT IN ('AURORA$ORB$UNAUTHENTICATED','BFG','ARCLOGIN','OUTLN','PERFSTAT','QUEST','SYS','SYSTEM','REPADMIN','MANAGER','CPLADMIN')
  AND INDEX_NAME NOT LIKE '%$%'
MINUS
SELECT OWNER||'.'||INDEX_NAME INDEX_NAME
  FROM DBA_INDEXES@TL11
 WHERE OWNER NOT IN ('AURORA$ORB$UNAUTHENTICATED','BFG','ARCLOGIN','OUTLN','PERFSTAT','QUEST','SYS','SYSTEM','REPADMIN','MANAGER','CPLADMIN')
  AND INDEX_NAME NOT LIKE '%$%'
/
