CREATE TABLE CATEGORIA
(
  CODIGO              NUMBER(19)                NOT NULL,
  DATAFINALVIGENCIA   DATE,
  DATAINICIOVIGENCIA  DATE,
  DESCRICAO           VARCHAR2(255 BYTE),
  EDICAO              NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLASSENACIONAL
(
  ID         NUMBER(19)                         NOT NULL,
  CODIGO     NUMBER(19),
  DESCRICAO  VARCHAR2(255 BYTE),
  TEXTO      VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLASSENICE
(
  CODIGO     NUMBER(19)                         NOT NULL,
  EDICAO     NUMBER(19)                         NOT NULL,
  DESCRICAO  VARCHAR2(255 BYTE),
  TIPO       VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DIVISAO
(
  CODIGO            NUMBER(19)                  NOT NULL,
  DESCRICAO         VARCHAR2(255 BYTE),
  EDICAO            NUMBER(19),
  NUMERO            NUMBER(19),
  CATEGORIA_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ESPECIFICACAO
(
  CODIGO              NUMBER(19)                NOT NULL,
  DATAFINALVIGENCIA   DATE,
  DATAINICIOVIGENCIA  DATE,
  DESCRICAO           VARCHAR2(255 BYTE),
  INDICATIVOAUXILIAR  VARCHAR2(255 BYTE),
  CLASSENICE_CODIGO   NUMBER(19),
  CLASSENICE_EDICAO   NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ESPECIFICACAOCLASSENACIONAL
(
  ID                   NUMBER(19)               NOT NULL,
  CODIGOCLASSE         NUMBER(19),
  CODIGOESPECIFICACAO  NUMBER(19),
  DESCRICAO            VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE NATUREZA
(
  CODIGO     CHAR(1 BYTE)                       NOT NULL,
  DESCRICAO  VARCHAR2(255 BYTE),
  SIGLA      VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE NOTACATEGORIA
(
  CODIGO            NUMBER(19)                  NOT NULL,
  DESCRICAO         VARCHAR2(255 BYTE),
  EDICAO            NUMBER(19),
  CATEGORIA_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE NOTADIVISAO
(
  CODIGO          NUMBER(19)                    NOT NULL,
  DESCRICAO       VARCHAR2(255 BYTE),
  DIVISAO_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PAGINA
(
  ID     NUMBER(19)                             NOT NULL,
  NOME   VARCHAR2(255 BYTE),
  ORDEM  NUMBER(10)                             NOT NULL
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PAIS
(
  ID                  NUMBER(19)                NOT NULL,
  INDICATIVOSITUACAO  VARCHAR2(255 BYTE)        DEFAULT '1',
  NOME                VARCHAR2(255 BYTE),
  SIGLA               VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SOLICITACAOPAPEL
(
  ID                    NUMBER                  NOT NULL,
  CAMINHOIMAGEM         VARCHAR2(255 BYTE),
  CAMINHOSTORAGE        VARCHAR2(255 BYTE),
  NOMEARQUIVO           VARCHAR2(255 BYTE),
  NUMEROVOLUME          NUMBER(38),
  CODIGODIRETORIA       NUMBER(38),
  NUMEROPROCESSO        VARCHAR2(255 BYTE),
  NUMEROGRU             VARCHAR2(255 BYTE),
  NUMEROPROTOCOLO       VARCHAR2(255 BYTE),
  DATAPAGAMENTOGRU      DATE,
  DATAENVIOSOLICITACAO  DATE,
  TIPOSOLICITACAO       NUMBER(10)              NOT NULL,
  CODIGOSERVICO         NUMBER(19),
  RAMIFICACAOSERVICO    NUMBER(19),
  STATUS                VARCHAR2(255 BYTE),
  VALORGUIA             NUMBER(19,2),
  APRESENTACAO_CODIGO   CHAR(1 BYTE),
  NATUREZA_CODIGO       CHAR(1 BYTE),
  TAMANHOARQUIVOORIGEM  NUMBER(22),
  QUANTIDADEPAGINAS     NUMBER(22)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOGMIGRACAO
(
  ID               NUMBER(38)                   NOT NULL,
  NUMEROPROCESSO   VARCHAR2(255 BYTE),
  NUMEROPROTOCOLO  VARCHAR2(255 BYTE),
  MENSAGEMDOIPAS   VARCHAR2(255 BYTE)           NOT NULL,
  DATA             DATE
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE INDICATIVOTIPOSERVICO
(
  CODIGO     NUMBER(19)                         NOT NULL,
  DESCRICAO  VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USUARIO
(
  ID                NUMBER(19),
  APLICACAO         VARCHAR2(255 BYTE),
  DATA              DATE,
  DESCRICAOERRO     VARCHAR2(255 BYTE),
  HOST              VARCHAR2(255 BYTE),
  IP                VARCHAR2(255 BYTE),
  LOGIN             VARCHAR2(255 BYTE),
  TIPOLOGIN         NUMBER(10),
  TOKENAUTORIZACAO  VARCHAR2(255 BYTE),
  NUMEROGRU         VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SECAO
(
  CODIGO              NUMBER(19)                NOT NULL,
  DESCRICAO           VARCHAR2(255 BYTE),
  INDICATIVOAUXILIAR  CHAR(1 BYTE),
  NUMERO              NUMBER(19),
  DIVISAO_CODIGO      NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SERIALPROCESSO
(
  SERIAL     NUMBER(19)                         NOT NULL,
  NUMEROGRU  VARCHAR2(20 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SERIALPROTOCOLO
(
  SERIAL     NUMBER(19)                         NOT NULL,
  NUMEROGRU  VARCHAR2(20 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SERVICOPAGINA
(
  CODIGOSERVICO  VARCHAR2(255 BYTE),
  VALIDACAO      NUMBER(10),
  PAGINA_ID      NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIPOANEXO
(
  CODIGO      NUMBER(19)                        NOT NULL,
  DESCRICAO   VARCHAR2(255 BYTE),
  ABREVIACAO  VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIPOANEXOSOLICITACAO
(
  CODIGOSERVICO     VARCHAR2(255 BYTE)          NOT NULL,
  OBRIGATORIO       CHAR(1 BYTE)                NOT NULL,
  TIPOANEXO_CODIGO  NUMBER(19)                  NOT NULL
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TIPOCERTIDAOBUSCA
(
  ID    NUMBER(19)                              NOT NULL,
  TIPO  VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SERVICO
(
  CODIGO     VARCHAR2(10 BYTE)                  NOT NULL,
  DESCRICAO  VARCHAR2(255 BYTE),
  NATUREZA   VARCHAR2(1 BYTE),
  APRESENT   VARCHAR2(1 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOGVISTA
(
  CODIGO                   NUMBER(19)           NOT NULL,
  DATALOG                  DATE,
  LOGIN                    VARCHAR2(255 BYTE),
  NUMEROGRU                VARCHAR2(255 BYTE),
  NUMEROPROCESSOPROTOCOLO  VARCHAR2(255 BYTE),
  STATUS                   CHAR(1 BYTE)         NOT NULL
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APRESENTACAO
(
  CODIGO       CHAR(1 BYTE)                     NOT NULL,
  DESCRICAO    VARCHAR2(255 BYTE),
  SIGLANOIPAS  CHAR(1 BYTE)                     NOT NULL,
  SIGLANOV2    CHAR(1 BYTE)                     NOT NULL
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SYS_C0031033 ON APRESENTACAO
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031035 ON CATEGORIA
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031044 ON CLASSENICE
(CODIGO, EDICAO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031046 ON DIVISAO
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031048 ON ESPECIFICACAO
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          320K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031069 ON NATUREZA
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031078 ON PAGINA
(ID)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031080 ON PAIS
(ID)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031086 ON SECAO
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031097 ON TIPOANEXO
(CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE UNIQUE INDEX SYS_C0031100 ON TIPOANEXOSOLICITACAO
(CODIGOSERVICO, TIPOANEXO_CODIGO)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE TABLE ITEMCLASSEVIENA
(
  ID                NUMBER(19)                  NOT NULL,
  CATEGORIA_CODIGO  NUMBER(19),
  DIVISAO_CODIGO    NUMBER(19),
  SECAO_CODIGO      NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE NOTASECAO
(
  CODIGO        NUMBER(19)                      NOT NULL,
  DESCRICAO     VARCHAR2(255 BYTE),
  SECAO_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SOLICITACAO
(
  CODIGO                       NUMBER(19)       NOT NULL,
  CODIGOSERVICO                NUMBER(19),
  DATAENVIOSOLICITACAO         DATE,
  DATAPAGAMENTOGRU             DATE,
  NOMEPDFFINAL                 VARCHAR2(255 BYTE),
  NUMEROGRU                    VARCHAR2(255 BYTE),
  NUMEROPROCESSO               VARCHAR2(9 BYTE),
  RAMIFICACAOSERVICO           NUMBER(19),
  STATUS                       VARCHAR2(255 BYTE),
  TIPOSOLICITACAO              NUMBER(10)       NOT NULL,
  VALORGUIA                    NUMBER(19,2),
  APRESENTACAO_CODIGO          CHAR(1 BYTE),
  NATUREZA_CODIGO              CHAR(1 BYTE),
  NUMEROPROTOCOLO              VARCHAR2(255 BYTE),
  TAMANHOPDFFINAL              NUMBER(19),
  DATAULTIMAASSINATURADIGITAL  DATE,
  HASH                         CLOB,
  NUMEROPAGINAS                NUMBER(19),
  PATHPDFFINAL                 VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
LOB (HASH) STORE AS 
      ( TABLESPACE  TBS_DADOS_MARCAS_01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  0
        NOCACHE
        NOLOGGING
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TEXTOESPECIFICACAO
(
  ID                  NUMBER(19)                NOT NULL,
  TEXTOEXTENSO        CLOB,
  CLASSENICE_CODIGO   NUMBER(19),
  CLASSENICE_EDICAO   NUMBER(19),
  SOLICITACAO_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
LOB (TEXTOEXTENSO) STORE AS 
      ( TABLESPACE  TBS_DADOS_MARCAS_01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        NOLOGGING
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ANEXO
(
  CODIGO              NUMBER(19)                NOT NULL,
  DESCRICAO           VARCHAR2(255 BYTE),
  NOMEARQUIVO         VARCHAR2(255 BYTE),
  PATH                VARCHAR2(255 BYTE),
  TIPOARQUIVO         VARCHAR2(255 BYTE),
  UUID                VARCHAR2(255 BYTE),
  SOLICITACAO_CODIGO  NUMBER(19),
  TIPOANEXO_CODIGO    NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE DADOSCLIENTE
(
  ID                  NUMBER(19)                NOT NULL,
  CEP                 VARCHAR2(255 BYTE),
  CIDADE              VARCHAR2(255 BYTE),
  CODIGO              NUMBER(10),
  CODIGOPAIS          VARCHAR2(255 BYTE),
  ENDERECO            VARCHAR2(255 BYTE),
  NOME                VARCHAR2(255 BYTE),
  UF                  VARCHAR2(255 BYTE),
  SOLICITACAO_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MARCA
(
  CODIGO               NUMBER(19)               NOT NULL,
  NOME                 VARCHAR2(255 BYTE),
  SERVICOCERTIFICACAO  VARCHAR2(255 BYTE),
  TRADUCAO             VARCHAR2(255 BYTE),
  SOLICITACAO_CODIGO   NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MARCAESPECIFICACAO
(
  ID                    NUMBER(19)              NOT NULL,
  ESPECIFICACAO_CODIGO  NUMBER(19)              NOT NULL,
  INDICATIVO_CODIGO     NUMBER(19)              NOT NULL,
  MARCA_CODIGO          NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MARCA_ITEMCLASSEVIENA
(
  MARCA_CODIGO     NUMBER(19)                   NOT NULL,
  CLASSESVIENA_ID  NUMBER(19)                   NOT NULL
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PETICAO
(
  CODIGO                   NUMBER(19)           NOT NULL,
  ASSUNTO                  VARCHAR2(255 BYTE),
  DATAENVIOPETICAO         DATE,
  NUMEROPROTOCOLOOPONENTE  VARCHAR2(255 BYTE),
  NUMERORPI                VARCHAR2(255 BYTE),
  TEXTOPETICAO             CLOB,
  SOLICITACAO_CODIGO       NUMBER(19),
  NUMEROPROTOCOLOANTERIOR  VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
LOB (TEXTOPETICAO) STORE AS 
      ( TABLESPACE  TBS_DADOS_MARCAS_01 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        NOCACHE
        NOLOGGING
        STORAGE    (
                    INITIAL          64K
                    MINEXTENTS       1
                    MAXEXTENTS       2147483645
                    PCTINCREASE      0
                    BUFFER_POOL      DEFAULT
                   )
      )
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PRIORIDADEUNIONISTA
(
  CODIGO          NUMBER(19)                    NOT NULL,
  DATADEPOSITO    DATE,
  NUMEROREGISTRO  VARCHAR2(255 BYTE),
  MARCA_CODIGO    NUMBER(19),
  PAIS_ID         NUMBER(19),
  UUID            VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE PRIORIDADEUNIONISTAPETICAO
(
  CODIGO          NUMBER(19)                    NOT NULL,
  DATADEPOSITO    DATE,
  NUMEROREGISTRO  VARCHAR2(255 BYTE),
  PAIS_ID         NUMBER(19),
  PETICAO_CODIGO  NUMBER(19),
  UUID            VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TRANSFERENCIAPROCESSO
(
  ID                NUMBER(19)                  NOT NULL,
  NOMEMARCA         VARCHAR2(255 BYTE),
  NOMETITULARMARCA  VARCHAR2(255 BYTE),
  NUMEROPROCESSO    VARCHAR2(255 BYTE),
  PETICAO_CODIGO    NUMBER(19),
  UUID              VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX SYS_C0032166 ON MARCA_ITEMCLASSEVIENA
(CLASSESVIENA_ID)
NOLOGGING
TABLESPACE TBS_DADOS_MARCAS_01
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE TABLE ALTERACAONOMERAZAO
(
  ID              NUMBER(19)                    NOT NULL,
  CEP             VARCHAR2(255 BYTE),
  ENDERECO        VARCHAR2(255 BYTE),
  NOME            VARCHAR2(255 BYTE),
  PETICAO_CODIGO  NUMBER(19),
  PAIS_ID         NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CERTIDAOBUSCA
(
  ID                    NUMBER(19)              NOT NULL,
  CONTEUDOCERTIDAO      VARCHAR2(255 BYTE),
  PETICAO_CODIGO        NUMBER(19),
  TIPOCERTIDAOBUSCA_ID  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLASSENACIONAL05
(
  ID                   NUMBER(19)               NOT NULL,
  CODIGOCLASSE         NUMBER(19),
  CODIGOESPECIFICACAO  NUMBER(19),
  DESCRICAO            VARCHAR2(255 BYTE),
  PETICAO_CODIGO       NUMBER(19),
  UUID                 VARCHAR2(255 BYTE)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE CLASSENICEPETICAO
(
  ID                 NUMBER(19)                 NOT NULL,
  CLASSENICE_CODIGO  NUMBER(19),
  CLASSENICE_EDICAO  NUMBER(19),
  PETICAO_CODIGO     NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE MARCAPETICAO
(
  CODIGO          NUMBER(19)                    NOT NULL,
  NOME            VARCHAR2(255 BYTE),
  TRADUCAO        VARCHAR2(255 BYTE),
  PETICAO_CODIGO  NUMBER(19)
)
TABLESPACE TBS_DADOS_MARCAS_01
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOLOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE CATEGORIA ADD (
  CONSTRAINT SYS_C0031035
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE CLASSENICE ADD (
  CONSTRAINT SYS_C0031044
 PRIMARY KEY
 (CODIGO, EDICAO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE DIVISAO ADD (
  CONSTRAINT SYS_C0031046
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE ESPECIFICACAO ADD (
  CONSTRAINT SYS_C0031048
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          320K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE NATUREZA ADD (
  CONSTRAINT SYS_C0031069
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PAGINA ADD (
  CONSTRAINT SYS_C0031078
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PAIS ADD (
  CONSTRAINT SYS_C0031080
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE SOLICITACAOPAPEL ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE LOGMIGRACAO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE INDICATIVOTIPOSERVICO ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE SECAO ADD (
  CONSTRAINT SYS_C0031086
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          128K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE SERIALPROCESSO ADD (
  PRIMARY KEY
 (SERIAL)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE SERIALPROTOCOLO ADD (
  PRIMARY KEY
 (SERIAL)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE TIPOANEXO ADD (
  CONSTRAINT SYS_C0031097
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE TIPOANEXOSOLICITACAO ADD (
  CONSTRAINT SYS_C0031100
 PRIMARY KEY
 (CODIGOSERVICO, TIPOANEXO_CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE TIPOCERTIDAOBUSCA ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE LOGVISTA ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE APRESENTACAO ADD (
  CONSTRAINT SYS_C0031033
 PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE ITEMCLASSEVIENA ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE SOLICITACAO ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE TEXTOESPECIFICACAO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE ANEXO ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE DADOSCLIENTE ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE MARCA ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE MARCAESPECIFICACAO ADD (
  CHECK ("MARCA_CODIGO" IS NOT NULL));

ALTER TABLE MARCAESPECIFICACAO ADD (
  CHECK ("MARCA_CODIGO" IS NOT NULL));

ALTER TABLE MARCAESPECIFICACAO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE MARCA_ITEMCLASSEVIENA ADD (
  CONSTRAINT SYS_C0032166
 UNIQUE (CLASSESVIENA_ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PETICAO ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PRIORIDADEUNIONISTA ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE PRIORIDADEUNIONISTAPETICAO ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE TRANSFERENCIAPROCESSO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE ALTERACAONOMERAZAO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE CERTIDAOBUSCA ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE CLASSENACIONAL05 ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE CLASSENICEPETICAO ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE MARCAPETICAO ADD (
  PRIMARY KEY
 (CODIGO)
    USING INDEX 
    TABLESPACE TBS_DADOS_MARCAS_01
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ));


ALTER TABLE DIVISAO ADD (
  CONSTRAINT FKC704E2C95A94AB4F 
 FOREIGN KEY (CATEGORIA_CODIGO) 
 REFERENCES CATEGORIA (CODIGO));


ALTER TABLE ESPECIFICACAO ADD (
  CONSTRAINT FK18158C715E1C77D 
 FOREIGN KEY (CLASSENICE_CODIGO, CLASSENICE_EDICAO) 
 REFERENCES CLASSENICE (CODIGO,EDICAO));


ALTER TABLE NOTACATEGORIA ADD (
  CONSTRAINT FKDE2E8CC55A94AB4F 
 FOREIGN KEY (CATEGORIA_CODIGO) 
 REFERENCES CATEGORIA (CODIGO));


ALTER TABLE NOTADIVISAO ADD (
  CONSTRAINT FK9BDFB2FB84CAC44F 
 FOREIGN KEY (DIVISAO_CODIGO) 
 REFERENCES DIVISAO (CODIGO));


ALTER TABLE SECAO ADD (
  CONSTRAINT FK4C1081F84CAC44F 
 FOREIGN KEY (DIVISAO_CODIGO) 
 REFERENCES DIVISAO (CODIGO));


ALTER TABLE SERVICOPAGINA ADD (
  CONSTRAINT FKBF47AF059719DC63 
 FOREIGN KEY (PAGINA_ID) 
 REFERENCES PAGINA (ID));


ALTER TABLE TIPOANEXOSOLICITACAO ADD (
  CONSTRAINT FKB827CA7444A62F 
 FOREIGN KEY (TIPOANEXO_CODIGO) 
 REFERENCES TIPOANEXO (CODIGO));


ALTER TABLE ITEMCLASSEVIENA ADD (
  CONSTRAINT FKAC049A255A94AB4F 
 FOREIGN KEY (CATEGORIA_CODIGO) 
 REFERENCES CATEGORIA (CODIGO));

ALTER TABLE ITEMCLASSEVIENA ADD (
  CONSTRAINT FKAC049A2584CAC44F 
 FOREIGN KEY (DIVISAO_CODIGO) 
 REFERENCES DIVISAO (CODIGO));

ALTER TABLE ITEMCLASSEVIENA ADD (
  CONSTRAINT FKAC049A25BBE4F94F 
 FOREIGN KEY (SECAO_CODIGO) 
 REFERENCES SECAO (CODIGO));


ALTER TABLE NOTASECAO ADD (
  CONSTRAINT FKDA163CD1BBE4F94F 
 FOREIGN KEY (SECAO_CODIGO) 
 REFERENCES SECAO (CODIGO));


ALTER TABLE SOLICITACAO ADD (
  CONSTRAINT FK88FE3E855FFB6E21 
 FOREIGN KEY (APRESENTACAO_CODIGO) 
 REFERENCES APRESENTACAO (CODIGO));

ALTER TABLE SOLICITACAO ADD (
  CONSTRAINT FK88FE3E85EFD21E21 
 FOREIGN KEY (NATUREZA_CODIGO) 
 REFERENCES NATUREZA (CODIGO));


ALTER TABLE TEXTOESPECIFICACAO ADD (
  CONSTRAINT FKB75AB34515E1C77D 
 FOREIGN KEY (CLASSENICE_CODIGO, CLASSENICE_EDICAO) 
 REFERENCES CLASSENICE (CODIGO,EDICAO));

ALTER TABLE TEXTOESPECIFICACAO ADD (
  CONSTRAINT FKB75AB345C8EA254F 
 FOREIGN KEY (SOLICITACAO_CODIGO) 
 REFERENCES SOLICITACAO (CODIGO));


ALTER TABLE ANEXO ADD (
  CONSTRAINT FK3C782AFC8EA254F 
 FOREIGN KEY (SOLICITACAO_CODIGO) 
 REFERENCES SOLICITACAO (CODIGO));

ALTER TABLE ANEXO ADD (
  CONSTRAINT FK3C782AF7444A62F 
 FOREIGN KEY (TIPOANEXO_CODIGO) 
 REFERENCES TIPOANEXO (CODIGO));


ALTER TABLE DADOSCLIENTE ADD (
  CONSTRAINT FK6CDF3FEFC8EA254F 
 FOREIGN KEY (SOLICITACAO_CODIGO) 
 REFERENCES SOLICITACAO (CODIGO));


ALTER TABLE MARCA ADD (
  CONSTRAINT FK46AE21CC8EA254F 
 FOREIGN KEY (SOLICITACAO_CODIGO) 
 REFERENCES SOLICITACAO (CODIGO));


ALTER TABLE MARCAESPECIFICACAO ADD (
  CONSTRAINT FK7997C42BAF56054F 
 FOREIGN KEY (ESPECIFICACAO_CODIGO) 
 REFERENCES ESPECIFICACAO (CODIGO));

ALTER TABLE MARCAESPECIFICACAO ADD (
  CONSTRAINT FK7997C42BC7558E0E 
 FOREIGN KEY (INDICATIVO_CODIGO) 
 REFERENCES INDICATIVOTIPOSERVICO (CODIGO));

ALTER TABLE MARCAESPECIFICACAO ADD (
  CONSTRAINT FK7997C42B45832AF 
 FOREIGN KEY (MARCA_CODIGO) 
 REFERENCES MARCA (CODIGO));


ALTER TABLE MARCA_ITEMCLASSEVIENA ADD (
  CONSTRAINT FK1A211A0254463077 
 FOREIGN KEY (CLASSESVIENA_ID) 
 REFERENCES ITEMCLASSEVIENA (ID));

ALTER TABLE MARCA_ITEMCLASSEVIENA ADD (
  CONSTRAINT FK1A211A0245832AF 
 FOREIGN KEY (MARCA_CODIGO) 
 REFERENCES MARCA (CODIGO));


ALTER TABLE PETICAO ADD (
  CONSTRAINT FK3ADFDC47C8EA254F 
 FOREIGN KEY (SOLICITACAO_CODIGO) 
 REFERENCES SOLICITACAO (CODIGO));


ALTER TABLE PRIORIDADEUNIONISTA ADD (
  CONSTRAINT FK4D2D1BA945832AF 
 FOREIGN KEY (MARCA_CODIGO) 
 REFERENCES MARCA (CODIGO));

ALTER TABLE PRIORIDADEUNIONISTA ADD (
  CONSTRAINT FK4D2D1BA95077A683 
 FOREIGN KEY (PAIS_ID) 
 REFERENCES PAIS (ID));


ALTER TABLE PRIORIDADEUNIONISTAPETICAO ADD (
  CONSTRAINT FK8475007E5077A683 
 FOREIGN KEY (PAIS_ID) 
 REFERENCES PAIS (ID));

ALTER TABLE PRIORIDADEUNIONISTAPETICAO ADD (
  CONSTRAINT FK8475007E8104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO));


ALTER TABLE TRANSFERENCIAPROCESSO ADD (
  CONSTRAINT FKF5B857478104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO));


ALTER TABLE ALTERACAONOMERAZAO ADD (
  CONSTRAINT FK4D87EFDA5077A683 
 FOREIGN KEY (PAIS_ID) 
 REFERENCES PAIS (ID));

ALTER TABLE ALTERACAONOMERAZAO ADD (
  CONSTRAINT FK4D87EFDA8104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO));


ALTER TABLE CERTIDAOBUSCA ADD (
  CONSTRAINT FKA50638118104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO));

ALTER TABLE CERTIDAOBUSCA ADD (
  CONSTRAINT FKA50638114B706451 
 FOREIGN KEY (TIPOCERTIDAOBUSCA_ID) 
 REFERENCES TIPOCERTIDAOBUSCA (ID));


ALTER TABLE CLASSENACIONAL05 ADD (
  CONSTRAINT FK1D21EE558104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO) DISABLE);


ALTER TABLE CLASSENICEPETICAO ADD (
  CONSTRAINT FK13B10DFD15E1C77D 
 FOREIGN KEY (CLASSENICE_CODIGO, CLASSENICE_EDICAO) 
 REFERENCES CLASSENICE (CODIGO,EDICAO));

ALTER TABLE CLASSENICEPETICAO ADD (
  CONSTRAINT FK13B10DFD8104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO));


ALTER TABLE MARCAPETICAO ADD (
  CONSTRAINT FK7173A2AB8104BA8F 
 FOREIGN KEY (PETICAO_CODIGO) 
 REFERENCES PETICAO (CODIGO));
