var OTN_ALL_CLOSED_NODES = [
		["SERVICES", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Downloads", null, "_top", 
				["Database", "/technology/software/products/database/oracle10g/index.html", "_top"],
				["Application Server", "/technology/software/products/ias/index.html", "_top"],
				["Enterprise Manager ", "/technology/software/products/oem/index.html", "_top"],
				["Developer Suite ", "/technology/software/products/ids/index.html", "_top"],
				["JDeveloper", "/technology/software/products/jdev/index.html", "_top"],
				["Collaboration Suite ", "/technology/software/products/cs/index.html", "_top"],
				["More...", "/technology/software/index.html", "_top"]
		],
			["Documentation", null, "_top", 
				["Database", "/technology/documentation/database10g.html", "_top"],
				["Application Server", "/technology/documentation/appserver1012.html", "_top"],
				["Enterprise Manager", "/technology/documentation/oem.html", "_top"],
				["Developer Suite ", "/technology/documentation/dev10g.html", "_top"],
				["JDeveloper", "/technology/documentation/9i_jdev.html", "_top"],
				["Collaboration Suite", "/technology/documentation/collab.html", "_top"],
				["Applications", "/technology/documentation/applications.html", "_top"],
				["More...", "/technology/documentation/index.html", "_top"]
		],
			["Discussions", null , "_top", 
				["Products", "http://forums.oracle.com/forums/index.jsp?cat=9", "_top"],
				["Technologies", "http://forums.oracle.com/forums/index.jsp?cat=10", "_top"],
				["Member Services", "http://forums.oracle.com/forums/index.jsp?cat=32", "_top"],
				["Hosted Services", "http://forums.oracle.com/forums/index.jsp?cat=5", "_top"],
                ["More...", "http://forums.oracle.com/forums/index.jsp?cat=1", "_top"]
		],
			["Articles", null, "_top", 
				["Articles Index", "/technology/pub/articles/index.html", "_top"],
				["For Developers", "/technology/pub/articles/tech_dev.html", "_top"],
				["For DBAs", "/technology/pub/articles/tech_dba.html", "_top"],
				["Columns", "/technology/pub/columns/index.html", "_top"],
				["Personalities", "/technology/pub/columns/otn_persons.html", "_top"],
				["Oracle Mag. Current", "/technology/oramag/oracle/current.html", "_top"],
				["Oracle Mag. Archives", "/technology/oramag/oracle/index.html", "_top"],
				["Oracle Publishing", "http://www.oracle.com/oramag/index.html", "_top"],
				["Subscriptions", "http://www.submag.com/oracle?pk=OTNLHN", "_top"]
		],
			["Sample Code", null, "_top", 
				["Tutorials", "/technology/sample_code/tutorials/OTN_Tutorials.html", "_top"],
				["Code of the Week", "/technology/oramag/code/code.html", "_top"],
				["J2EE", "/technology/sample_code/tech/java/j2ee/index.html", "_top"],
				["JavaServer Pages", "/technology/sample_code/tech/java/jsps/index.html", "_top"],
				["JDBC & SQLJ", "/technology/sample_code/tech/java/sqlj_jdbc/index.html", "_top"],
				["ODP.NET", "/technology/sample_code/tech/windows/odpnet/index.html", "_top"],
				["PL/SQL", "/technology/sample_code/tech/pl_sql/index.html", "_top"],
				["Web Services", "/technology/sample_code/tech/java/web_services/index.html", "_top"],
				["XML", "/technology/sample_code/tech/xml/index.html ", "_top"],
				["More...", "/technology/sample_code/index.html", "_top"]
		],
			["Training", null, "_top", 
				["2 Day DBA", "http://download-west.oracle.com/docs/cd/B12037_01/server.101/b10742/toc.htm", "_top"],
				["Oracle By Example ", "/technology/obe/index.html", "_top"],
				["Oracle University", "/technology/training/index.html", "_top"],
				["Oracle 10g Books ", "http://www.oracle.com/elog/trackurl?d=http://otn.oracle.com/books/10g_books.html&di=2956393", "_top"]
		],
            ["Support", null, "_top", 
				["AskTom.com", "http://asktom.oracle.com/index.html", "_blank"],
                ["Hosted Development", "/technology/hosted_dev/index.html", "_top"],
                ["Oracle Consulting", "/technology/consulting/index.html", "_top"],
				["Patch Sets", "/technology/support/patches.htm", "_top"],
				["Product Certifications", "/technology/support/metalink/index.html", "_top"],
                ["Security Alerts", "/technology/deploy/security/alerts.htm", "_top"],
	    		["Support Contacts", "http://www.oracle.com/support/contact.html", "_top"]
	   ],
	],
		["RESOURCES FOR", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Developers", "/technology/developer/index.html", "_top"],
			["DBAs", "/technology/dba/index.html", "_top"],
			["ISVs", "/technology/isv/index.html", "_top"],
			["Small & Midsize Businesses", "/technology/smb/index.html", "_top"],
			["Getting Started", "/technology/new/index.html", "_top",],
	]
];

var OTN_DOWNLOADS_NODES = [
		["SERVICES", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Downloads", "javascript:void(0);", null, {"format":{"expanded":true}},
				["Database", "/technology/software/products/database/oracle10g/index.html", "_top"],
				["Application Server", "/technology/software/products/ias/index.html", "_top"],
				["Enterprise Manager ", "/technology/software/products/oem/index.html", "_top"],
				["Developer Suite ", "/technology/software/products/ids/index.html", "_top"],
				["JDeveloper", "/technology/software/products/jdev/index.html", "_top"],
				["Collaboration Suite ", "/technology/software/products/cs/index.html", "_top"],
				["More...", "/technology/software/index.html", "_top"]
		],
			["Documentation", null, "_top", 
				["Database", "/technology/documentation/database10g.html", "_top"],
				["Application Server", "/technology/documentation/appserver1012.html", "_top"],
				["Enterprise Manager", "/technology/documentation/oem.html", "_top"],
				["Developer Suite ", "/technology/documentation/dev10g.html", "_top"],
				["JDeveloper", "/technology/documentation/9i_jdev.html", "_top"],
				["Collaboration Suite", "/technology/documentation/collab.html", "_top"],
				["Applications", "/technology/documentation/applications.html", "_top"],
				["More...", "/technology/documentation/index.html", "_top"]
		],
			["Discussions", null , "_top", 
				["Products", "http://forums.oracle.com/forums/index.jsp?cat=9", "_top"],
				["Technologies", "http://forums.oracle.com/forums/index.jsp?cat=10", "_top"],
				["Member Services", "http://forums.oracle.com/forums/index.jsp?cat=32", "_top"],
				["Hosted Services", "http://forums.oracle.com/forums/index.jsp?cat=5", "_top"],
                ["More...", "http://forums.oracle.com/forums/index.jsp?cat=1", "_top"]
		],
			["Articles", null, "_top", 
				["Articles Index", "/technology/pub/articles/index.html", "_top"],
				["For Developers", "/technology/pub/articles/tech_dev.html", "_top"],
				["For DBAs", "/technology/pub/articles/tech_dba.html", "_top"],
				["Columns", "/technology/pub/columns/index.html", "_top"],
				["Personalities", "/technology/pub/columns/otn_persons.html", "_top"],
				["Oracle Mag. Current", "/technology/oramag/oracle/current.html", "_top"],
				["Oracle Mag. Archives", "/technology/oramag/oracle/index.html", "_top"],
				["Oracle Publishing", "http://www.oracle.com/oramag/index.html", "_top"],
				["Subscriptions", "http://www.submag.com/oracle?pk=OTNLHN", "_top"]
		],
			["Sample Code", null, "_top", 
				["Tutorials", "/technology/sample_code/tutorials/OTN_Tutorials.html", "_top"],
				["Code of the Week", "/technology/oramag/code/code.html", "_top"],
				["J2EE", "/technology/sample_code/tech/java/j2ee/index.html", "_top"],
				["JavaServer Pages", "/technology/sample_code/tech/java/jsps/index.html", "_top"],
				["JDBC & SQLJ", "/technology/sample_code/tech/java/sqlj_jdbc/index.html", "_top"],
				["ODP.NET", "/technology/sample_code/tech/windows/odpnet/index.html", "_top"],
				["PL/SQL", "/technology/sample_code/tech/pl_sql/index.html", "_top"],
				["Web Services", "/technology/sample_code/tech/java/web_services/index.html", "_top"],
				["XML", "/technology/sample_code/tech/xml/index.html ", "_top"],
				["More...", "/technology/sample_code/index.html", "_top"]
		],
			["Training", null, "_top", 
				["2 Day DBA", "http://download-west.oracle.com/docs/cd/B12037_01/server.101/b10742/toc.htm", "_top"],
				["Oracle By Example ", "/technology/obe/index.html", "_top"],
				["Oracle University", "/technology/training/index.html", "_top"],
				["Oracle 10g Books ", "http://www.oracle.com/elog/trackurl?d=http://otn.oracle.com/books/10g_books.html&di=2956393", "_top"]
		],
		["Support", null, "_top", 
				["AskTom.com", "http://asktom.oracle.com/index.html", "_blank"],
                ["Hosted Development", "/technology/hosted_dev/index.html", "_top"],
                ["Oracle Consulting", "/technology/consulting/index.html", "_top"],
				["Patch Sets", "/technology/support/patches.htm", "_top"],
				["Product Certifications", "/technology/support/metalink/index.html", "_top"],
                ["Security Alerts", "/technology/deploy/security/alerts.htm", "_top"],
	    		["Support Contacts", "http://www.oracle.com/support/contact.html", "_top"]
	   ],
	],
		["RESOURCES FOR", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Developer", "/technology/developer/index.html", "_top"],
			["DBAs", "/technology/dba/index.html", "_top"],
			["ISVs", "/technology/isv/index.html", "_top"],
			["Small & Midsize Businesses", "/technology/smb/index.html", "_top"],
			["Getting Started", "/technology/new/index.html", "_top",], 
	]
];

var OTN_DOCUMENTATION_NODES = [
		["SERVICES", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Downloads", null, "_top", 
				["Database", "/technology/software/products/database/oracle10g/index.html", "_top"],
				["Application Server", "/technology/software/products/ias/index.html", "_top"],
				["Enterprise Manager ", "/technology/software/products/oem/index.html", "_top"],
				["Developer Suite ", "/technology/software/products/ids/index.html", "_top"],
				["JDeveloper", "/technology/software/products/jdev/index.html", "_top"],
				["Collaboration Suite ", "/technology/software/products/cs/index.html", "_top"],
				["More...", "/technology/software/index.html", "_top"]
		],
			["Documentation", "javascript:void(0);", null ,{"format":{"expanded":true}},  
				["Database", "/technology/documentation/database10g.html", "_top"],
				["Application Server", "/technology/documentation/appserver1012.html", "_top"],
				["Enterprise Manager", "/technology/documentation/oem.html", "_top"],
				["Developer Suite ", "/technology/documentation/dev10g.html", "_top"],
				["JDeveloper", "/technology/documentation/9i_jdev.html", "_top"],
				["Collaboration Suite", "/technology/documentation/collab.html", "_top"],
				["Applications", "/technology/documentation/applications.html", "_top"],
				["More...", "/technology/documentation/index.html", "_top"]
		],
			["Discussions", null , "_top", 
				["Products", "http://forums.oracle.com/forums/index.jsp?cat=9", "_top"],
				["Technologies", "http://forums.oracle.com/forums/index.jsp?cat=10", "_top"],
				["Member Services", "http://forums.oracle.com/forums/index.jsp?cat=32", "_top"],
				["Hosted Services", "http://forums.oracle.com/forums/index.jsp?cat=5", "_top"],
                ["More...", "http://forums.oracle.com/forums/index.jsp?cat=1", "_top"],
		],
			["Articles", null, "_top", 
				["Articles Index", "/technology/pub/articles/index.html", "_top"],
				["For Developers", "/technology/pub/articles/tech_dev.html", "_top"],
				["For DBAs", "/technology/pub/articles/tech_dba.html", "_top"],
				["Columns", "/technology/pub/columns/index.html", "_top"],
				["Personalities", "/technology/pub/columns/otn_persons.html", "_top"],
				["Oracle Mag. Current", "/technology/oramag/oracle/current.html", "_top"],
				["Oracle Mag. Archives", "/technology/oramag/oracle/index.html", "_top"],
				["Oracle Publishing", "http://www.oracle.com/oramag/index.html", "_top"],
				["Subscriptions", "http://www.submag.com/oracle?pk=OTNLHN", "_top"]
		],
			["Sample Code", null, "_top", 
				["Tutorials", "/technology/sample_code/tutorials/OTN_Tutorials.html", "_top"],
				["Code of the Week", "/technology/oramag/code/code.html", "_top"],
				["J2EE", "/technology/sample_code/tech/java/j2ee/index.html", "_top"],
				["JavaServer Pages", "/technology/sample_code/tech/java/jsps/index.html", "_top"],
				["JDBC & SQLJ", "/technology/sample_code/tech/java/sqlj_jdbc/index.html", "_top"],
				["ODP.NET", "/technology/sample_code/tech/windows/odpnet/index.html", "_top"],
				["PL/SQL", "/technology/sample_code/tech/pl_sql/index.html", "_top"],
				["Web Services", "/technology/sample_code/tech/java/web_services/index.html", "_top"],
				["XML", "/technology/sample_code/tech/xml/index.html ", "_top"],
				["More...", "/technology/sample_code/index.html", "_top"]
		],
			["Training", null, "_top", 
				["2 Day DBA", "http://download-west.oracle.com/docs/cd/B12037_01/server.101/b10742/toc.htm", "_top"],
				["Oracle By Example ", "/technology/obe/index.html", "_top"],
				["Oracle University", "/technology/training/index.html", "_top"],
				["Oracle 10g Books ", "http://www.oracle.com/elog/trackurl?d=http://otn.oracle.com/books/10g_books.html&di=2956393", "_top"]
		],
		["Support", null, "_top", 
				["AskTom.com", "http://asktom.oracle.com/index.html", "_blank"],
                ["Hosted Development", "/technology/hosted_dev/index.html", "_top"],
                ["Oracle Consulting", "/technology/consulting/index.html", "_top"],
				["Patch Sets", "/technology/support/patches.htm", "_top"],
				["Product Certifications", "/technology/support/metalink/index.html", "_top"],
                ["Security Alerts", "/technology/deploy/security/alerts.htm", "_top"],
	    		["Support Contacts", "http://www.oracle.com/support/contact.html", "_top"]
	   ],
	],
		["RECOURCES FOR", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Developer", "/technology/developer/index.html", "_top"],
			["DBAs", "/technology/dba/index.html", "_top"],
			["ISVs", "/technology/isv/index.html", "_top"],
			["Small & Midsize Businesses", "/technology/smb/index.html", "_top"],
			["Getting Started", "/technology/new/index.html", "_top",], 
	]
];

var OTN_ARTICLES_NODES = [
		["SERVICES", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Downloads", null, "_top", 
				["Database", "/technology/software/products/database/oracle10g/index.html", "_top"],
				["Application Server", "/technology/software/products/ias/index.html", "_top"],
				["Enterprise Manager ", "/technology/software/products/oem/index.html", "_top"],
				["Developer Suite ", "/technology/software/products/ids/index.html", "_top"],
				["JDeveloper", "/technology/software/products/jdev/index.html", "_top"],
				["Collaboration Suite ", "/technology/software/products/cs/index.html", "_top"],
				["More...", "/technology/software/index.html", "_top"]
		],
			["Documentation", null, "_top", 
				["Database", "/technology/documentation/database10g.html", "_top"],
				["Application Server", "/technology/documentation/appserver1012.html", "_top"],
				["Enterprise Manager", "/technology/documentation/oem.html", "_top"],
				["Developer Suite ", "/technology/documentation/dev10g.html", "_top"],
				["JDeveloper", "/technology/documentation/9i_jdev.html", "_top"],
				["Collaboration Suite", "/technology/documentation/collab.html", "_top"],
				["Applications", "/technology/documentation/applications.html", "_top"],
				["More...", "/technology/documentation/index.html", "_top"]
		],
			["Discussions", null , "_top", 
				["Products", "http://forums.oracle.com/forums/index.jsp?cat=9", "_top"],
				["Technologies", "http://forums.oracle.com/forums/index.jsp?cat=10", "_top"],
				["Member Services", "http://forums.oracle.com/forums/index.jsp?cat=32", "_top"],
				["Hosted Services", "http://forums.oracle.com/forums/index.jsp?cat=5", "_top"],
                ["More...", "http://forums.oracle.com/forums/index.jsp?cat=1", "_top"]
		],
			["Articles", "javascript:void(0);", null ,{"format":{"expanded":true}},  
				["Articles Index", "/technology/pub/articles/index.html", "_top"],
				["For Developers", "/technology/pub/articles/tech_dev.html", "_top"],
				["For DBAs", "/technology/pub/articles/tech_dba.html", "_top"],
				["Columns", "/technology/pub/columns/index.html", "_top"],
				["Personalities", "/technology/pub/columns/otn_persons.html", "_top"],
				["Oracle Mag. Current", "/technology/oramag/oracle/current.html", "_top"],
				["Oracle Mag. Archives", "/technology/oramag/oracle/index.html", "_top"],
				["Oracle Publishing", "http://www.oracle.com/oramag/index.html", "_top"],
				["Subscriptions", "http://www.submag.com/oracle?pk=OTNLHN", "_top"]
		],
			["Sample Code", null, "_top", 
				["Tutorials", "/technology/sample_code/tutorials/OTN_Tutorials.html", "_top"],
				["Code of the Week", "/technology/oramag/code/code.html", "_top"],
				["J2EE", "/technology/sample_code/tech/java/j2ee/index.html", "_top"],
				["JavaServer Pages", "/technology/sample_code/tech/java/jsps/index.html", "_top"],
				["JDBC & SQLJ", "/technology/sample_code/tech/java/sqlj_jdbc/index.html", "_top"],
				["ODP.NET", "/technology/sample_code/tech/windows/odpnet/index.html", "_top"],
				["PL/SQL", "/technology/sample_code/tech/pl_sql/index.html", "_top"],
				["Web Services", "/technology/sample_code/tech/java/web_services/index.html", "_top"],
				["XML", "/technology/sample_code/tech/xml/index.html ", "_top"],
				["More...", "/technology/sample_code/index.html", "_top"]
		],
			["Training", null, "_top", 
				["2 Day DBA", "http://download-west.oracle.com/docs/cd/B12037_01/server.101/b10742/toc.htm", "_top"],
				["Oracle By Example ", "/technology/obe/index.html", "_top"],
				["Oracle University", "/technology/training/index.html", "_top"],
				["Oracle 10g Books ", "http://www.oracle.com/elog/trackurl?d=http://otn.oracle.com/books/10g_books.html&di=2956393", "_top"]
		],
		["Support", null, "_top", 
				["AskTom.com", "http://asktom.oracle.com/index.html", "_blank"],
                ["Hosted Development", "/technology/hosted_dev/index.html", "_top"],
                ["Oracle Consulting", "/technology/consulting/index.html", "_top"],
				["Patch Sets", "/technology/support/patches.htm", "_top"],
				["Product Certifications", "/technology/support/metalink/index.html", "_top"],
                ["Security Alerts", "/technology/deploy/security/alerts.htm", "_top"],
	    		["Support Contacts", "http://www.oracle.com/support/contact.html", "_top"]
	   ],
	],
		["RESOURCES FOR", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Developer", "/technology/developer/index.html", "_top"],
			["DBAs", "/technology/dba/index.html", "_top"],
			["ISVs", "/technology/isv/index.html", "_top"],
			["Small & Midsize Businesses", "/technology/smb/index.html", "_top"],
			["Getting Started", "/technology/new/index.html", "_top",],
	]
];

var OTN_SAMPLE_CODE_NODES = [
		["SERVICES", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Downloads", null, "_top", 
				["Database", "/technology/software/products/database/oracle10g/index.html", "_top"],
				["Application Server", "/technology/software/products/ias/index.html", "_top"],
				["Enterprise Manager ", "/technology/software/products/oem/index.html", "_top"],
				["Developer Suite ", "/technology/software/products/ids/index.html", "_top"],
				["JDeveloper", "/technology/software/products/jdev/index.html", "_top"],
				["Collaboration Suite ", "/technology/software/products/cs/index.html", "_top"],
				["More...", "/technology/software/index.html", "_top"]
		],
			["Documentation", null, "_top", 
				["Database", "/technology/documentation/database10g.html", "_top"],
				["Application Server", "/technology/documentation/appserver1012.html", "_top"],
				["Enterprise Manager", "/technology/documentation/oem.html", "_top"],
				["Developer Suite ", "/technology/documentation/dev10g.html", "_top"],
				["JDeveloper", "/technology/documentation/9i_jdev.html", "_top"],
				["Collaboration Suite", "/technology/documentation/collab.html", "_top"],
				["Applications", "/technology/documentation/applications.html", "_top"],
				["More...", "/technology/documentation/index.html", "_top"]
		],
			["Discussions", null , "_top", 
				["Products", "http://forums.oracle.com/forums/index.jsp?cat=9", "_top"],
				["Technologies", "http://forums.oracle.com/forums/index.jsp?cat=10", "_top"],
				["Member Feedback", "http://forums.oracle.com/forums/index.jsp?cat=32", "_top"],
				["Hosted Services", "http://forums.oracle.com/forums/index.jsp?cat=5", "_top"],
                ["More...", "http://forums.oracle.com/forums/index.jsp?cat=1", "_top"]
		],
			["Articles", null, "_top", 
				["Articles Index", "/technology/pub/articles/index.html", "_top"],
				["For Developers", "/technology/pub/articles/tech_dev.html", "_top"],
				["For DBAs", "/technology/pub/articles/tech_dba.html", "_top"],
				["Columns", "/technology/pub/columns/index.html", "_top"],
				["Personalities", "/technology/pub/columns/otn_persons.html", "_top"],
				["Oracle Mag. Current", "/technology/oramag/oracle/current.html", "_top"],
				["Oracle Mag. Archives", "/technology/oramag/oracle/index.html", "_top"],
				["Oracle Publishing", "http://www.oracle.com/oramag/index.html", "_top"],
				["Subscriptions", "http://www.submag.com/oracle?pk=OTNLHN", "_top"]
		],
			["Sample Code", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
				["Tutorials", "/technology/sample_code/tutorials/OTN_Tutorials.html", "_top"],
				["Code of the Week", "/technology/oramag/code/code.html", "_top"],
				["J2EE", "/technology/sample_code/tech/java/j2ee/index.html", "_top"],
				["JavaServer Pages", "/technology/sample_code/tech/java/jsps/index.html", "_top"],
				["JDBC & SQLJ", "/technology/sample_code/tech/java/sqlj_jdbc/index.html", "_top"],
				["ODP.NET", "/technology/sample_code/tech/windows/odpnet/index.html", "_top"],
				["PL/SQL", "/technology/sample_code/tech/pl_sql/index.html", "_top"],
				["Web Services", "/technology/sample_code/tech/java/web_services/index.html", "_top"],
				["XML", "/technology/sample_code/tech/xml/index.html ", "_top"],
				["More...", "/technology/sample_code/index.html", "_top"]
		],
			["Training", null, "_top", 
				["2 Day DBA", "http://download-west.oracle.com/docs/cd/B12037_01/server.101/b10742/toc.htm", "_top"],
				["Oracle By Example ", "/technology/obe/index.html", "_top"],
				["Oracle University", "/technology/training/index.html", "_top"],
				["Oracle 10g Books ", "http://www.oracle.com/elog/trackurl?d=http://otn.oracle.com/books/10g_books.html&di=2956393", "_top"]
		],
		["Support", null, "_top", 
				["AskTom.com", "http://asktom.oracle.com/index.html", "_blank"],
                ["Hosted Development", "/technology/hosted_dev/index.html", "_top"],
                ["Oracle Consulting", "/technology/consulting/index.html", "_top"],
				["Patch Sets", "/technology/support/patches.htm", "_top"],
				["Product Certifications", "/technology/support/metalink/index.html", "_top"],
                ["Security Alerts", "/technology/deploy/security/alerts.htm", "_top"],
	    		["Support Contacts", "http://www.oracle.com/support/contact.html", "_top"]
	   ],
	],
		["RESOURCES FOR", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Developer", "/technology/developer/index.html", "_top"],
			["DBAs", "/technology/dba/index.html", "_top"],
			["ISVs", "/technology/isv/index.html", "_top"],
			["Small & Midsize Businesses", "/technology/smb/index.html", "_top"],
			["Getting Started", "/technology/new/index.html", "_top",],
	]
];
var OTN_TRAINING_NODES = [
		["SERVICES", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Downloads", null, "_top", 
				["Database", "/technology/software/products/database/oracle10g/index.html", "_top"],
				["Application Server", "/technology/software/products/ias/index.html", "_top"],
				["Enterprise Manager ", "/technology/software/products/oem/index.html", "_top"],
				["Developer Suite ", "/technology/software/products/ids/index.html", "_top"],
				["JDeveloper", "/technology/software/products/jdev/index.html", "_top"],
				["Collaboration Suite ", "/technology/software/products/cs/index.html", "_top"],
				["More...", "/technology/software/index.html", "_top"]
		],
			["Documentation", null, "_top", 
				["Database", "/technology/documentation/database10g.html", "_top"],
				["Application Server", "/technology/documentation/appserver1012.html", "_top"],
				["Enterprise Manager", "/technology/documentation/oem.html", "_top"],
				["Developer Suite ", "/technology/documentation/dev10g.html", "_top"],
				["JDeveloper", "/technology/documentation/9i_jdev.html", "_top"],
				["Collaboration Suite", "/technology/documentation/collab.html", "_top"],
				["Applications", "/technology/documentation/applications.html", "_top"],
				["More...", "/technology/documentation/index.html", "_top"]
		],
			["Discussions", null , "_top", 
				["Products", "http://forums.oracle.com/forums/index.jsp?cat=9", "_top"],
				["Technologies", "http://forums.oracle.com/forums/index.jsp?cat=10", "_top"],
				["Member Feedback", "http://forums.oracle.com/forums/index.jsp?cat=32", "_top"],
				["Hosted Services", "http://forums.oracle.com/forums/index.jsp?cat=5", "_top"],
                ["More...", "http://forums.oracle.com/forums/index.jsp?cat=1", "_top"]
		],
			["Articles", null, "_top", 
				["Articles Index", "/technology/pub/articles/index.html", "_top"],
				["For Developers", "/technology/pub/articles/tech_dev.html", "_top"],
				["For DBAs", "/technology/pub/articles/tech_dba.html", "_top"],
				["Columns", "/technology/pub/columns/index.html", "_top"],
				["Personalities", "/technology/pub/columns/otn_persons.html", "_top"],
				["Oracle Mag. Current", "/technology/oramag/oracle/current.html", "_top"],
				["Oracle Mag. Archives", "/technology/oramag/oracle/index.html", "_top"],
				["Oracle Publishing", "http://www.oracle.com/oramag/index.html", "_top"],
				["Subscriptions", "http://www.submag.com/oracle?pk=OTNLHN", "_top"]
		],
			["Sample Code", null, "_top", 
				["Tutorials", "/technology/sample_code/tutorials/OTN_Tutorials.html", "_top"],
				["Code of the Week", "/technology/oramag/code/code.html", "_top"],
				["J2EE", "/technology/sample_code/tech/java/j2ee/index.html", "_top"],
				["JavaServer Pages", "/technology/sample_code/tech/java/jsps/index.html", "_top"],
				["JDBC & SQLJ", "/technology/sample_code/tech/java/sqlj_jdbc/index.html", "_top"],
				["ODP.NET", "/technology/sample_code/tech/windows/odpnet/index.html", "_top"],
				["PL/SQL", "/technology/sample_code/tech/pl_sql/index.html", "_top"],
				["Web Services", "/technology/sample_code/tech/java/web_services/index.html", "_top"],
				["XML", "/technology/sample_code/tech/xml/index.html ", "_top"],
				["More...", "/technology/sample_code/index.html", "_top"]
		],
			["Training", "javascript:void(0);", null ,{"format":{"expanded":true}},
				["2 Day DBA", "http://download-west.oracle.com/docs/cd/B12037_01/server.101/b10742/toc.htm", "_top"],
				["Oracle By Example ", "/technology/obe/index.html", "_top"],
				["Oracle University", "/technology/training/index.html", "_top"],
				["Oracle 10g Books ", "http://www.oracle.com/elog/trackurl?d=http://otn.oracle.com/books/10g_books.html&di=2956393", "_top"]
		],
		["Support", null, "_top", 
				["AskTom.com", "http://asktom.oracle.com/index.html", "_blank"],
                ["Hosted Development", "/technology/hosted_dev/index.html", "_top"],
                ["Oracle Consulting", "/technology/consulting/index.html", "_top"],
				["Patch Sets", "/technology/support/patches.htm", "_top"],
				["Product Certifications", "/technology/support/metalink/index.html", "_top"],
                ["Security Alerts", "/technology/deploy/security/alerts.htm", "_top"],
	    		["Support Contacts", "http://www.oracle.com/support/contact.html", "_top"]
	   ],
	],
		["RESOURCES FOR", "javascript:void(0);", null ,{"format":{"expanded":true}}, 
			["Developer", "/technology/developer/index.html", "_top"],
			["DBAs", "/technology/dba/index.html", "_top"],
			["ISVs", "/technology/isv/index.html", "_top"],
			["Small & Midsize Businesses", "/technology/smb/index.html", "_top"],
			["Getting Started", "/technology/new/index.html", "_top",],
	]
];
