-- Com buffer Pool

SELECT O.OWNER,OBJECT_NAME,S.BUFFER_POOL, COUNT(*) FROM V$BH BH,DBA_OBJECTS O,DBA_SEGMENTS S
  WHERE BH.OBJD = O.OBJECT_ID
 AND O.OWNER = S.OWNER
 AND O.OBJECT_NAME = S.SEGMENT_NAME
GROUP BY O.OWNER,OBJECT_NAME,BUFFER_POOL
HAVING COUNT(*) > 300
ORDER BY COUNT(*) DESC;  

-- Sem Buffer Pool
SELECT O.OWNER,OBJECT_NAME,COUNT(*) FROM V$BH BH,DBA_OBJECTS O
  WHERE BH.OBJD = O.OBJECT_ID
GROUP BY O.OWNER,OBJECT_NAME
HAVING COUNT(*) > 300
ORDER BY COUNT(*) DESC;  


SELECT NAME, 100-PHYSICAL_READS/(CONSISTENT_GETS+DB_BLOCK_GETS)*100 AS "Cache hit Ratio" FROM V$BUFFER_POOL_STATISTICS
where  CONSISTENT_GETS+DB_BLOCK_GETS <> 0


 