 COLUMN OBJECT_NAME FORMAT A30
 COLUMN OWNER FORMAT A15
 COLUMN OBJECT_TYPE FORMAT A12

 SELECT OBJECT_NAME,OWNER,OBJECT_TYPE,COUNT(*) AS BLOCOS
 FROM DBA_OBJECTS,X$BH
 WHERE OBJECT_ID = OBJ
 GROUP BY OBJECT_NAME,OWNER,OBJECT_TYPE
 HAVING COUNT(*) >= 400
 ORDER BY COUNT(*) DESC;

 COLUMN OBJECT_NAME CLEAR
 COLUMN OWNER CLEAR
 COLUMN OBJECT_TYPE CLEAR
