SELECT LPAD(' ',2*LEVEL)||OPERATION||' '||OPTIONS||' '||OBJECT_NAME QUERY_PLAN
  FROM PLAN_TABLE WHERE STATEMENT_ID = '&1'
  CONNECT BY PRIOR ID = PARENT_ID AND STATEMENT_ID = '&1'
  START WITH ID = 1
/
