SET LINESIZE 150
SET PAGESIZE 500

SET HEAD OFF
SET VERIFY OFF
SET ECHO OFF
SET FEEDBACK OFF

ACCEPT  BD CHAR PROMPT 'Digite o Banco : '

@&BD

SET HEAD OFF
SET VERIFY OFF
SET ECHO OFF
SET FEEDBACK OFF

ACCEPT  1 CHAR PROMPT 'Digite Novo Usuário : '
ACCEPT  2 CHAR PROMPT 'Digite Antigo Usuário : '

SELECT 'CREATE USER &1 IDENTIFIED BY &1;' FROM DUAL;

SELECT 'ALTER USER &1 DEFAULT TABLESPACE '||DEFAULT_TABLESPACE||' 
TEMPORARY TABLESPACE '||TEMPORARY_TABLESPACE||' 
QUOTA UNLIMITED ON '||DEFAULT_TABLESPACE||'
PROFILE '||PROFILE||'
PASSWORD EXPIRE;' FROM DBA_USERS
WHERE USERNAME = '&2';

SELECT 'GRANT '||GRANTED_ROLE||' TO &1;' FROM DBA_ROLE_PRIVS 
WHERE GRANTEE = '&2';

SELECT 'GRANT '||PRIVILEGE||' TO &1;' FROM DBA_SYS_PRIVS 
WHERE GRANTEE = '&2';

SELECT 'GRANT '||PRIVILEGE||' ON '||TABLE_NAME||' TO &1;' FROM DBA_TAB_PRIVS
WHERE GRANTEE = '&2'
AND PRIVILEGE NOT IN ('SELECT','DELETE','UPDATE','INSERT');


SELECT '**********************************************************************'
FROM DUAL;
SELECT '**************** COPIE AS LINHAS ACIMA E COLE ABAIXO. ****************' FROM DUAL;
SELECT '**********************************************************************' FROM DUAL;

SET FEEDBACK ON
SET HEAD ON
SET LINESIZE 150
