SQL> SELECT 'ALTER PROCEDURE ' || OBJECT_NAME || ' COMPILE;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'PROCEDURE';
SQL> 
SQL> SELECT 'ALTER PACKAGE ' || OBJECT_NAME || ' COMPILE;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'PACKAGE';
SQL> 
SQL> SELECT 'ALTER PACKAGE ' || OBJECT_NAME || ' COMPILE BODY;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'PACKAGE BODY';
SQL> 
SQL> SELECT 'ALTER VIEW "' || OBJECT_NAME || '" COMPILE;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'VIEW';
SQL> 
SQL> SELECT 'ALTER TRIGGER ' || OBJECT_NAME || ' COMPILE;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'TRIGGER';
SQL> 
SQL> SELECT 'ALTER JAVA CLASS "' || OBJECT_NAME || '" COMPILE;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'JAVA CLASS';
SQL> 
SQL> SELECT 'ALTER TYPE ' || OBJECT_NAME || ' COMPILE;'
  2  FROM USER_OBJECTS
  3  WHERE STATUS = 'INVALID'
  4  AND OBJECT_TYPE = 'TYPE';
SQL> 
SQL> SPOOL OFF
